In [1]:
import pandas as pd
import numpy as np

tmdb = pd.read_csv("tmdb_5000_movies.csv")
tmdb

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [2]:
import pandas as pd

# Example loading dataset
# tmdb = pd.read_csv('your_dataset_file.csv')

# Function to extract and join genre names
def extract_genre_names(genre_list):
    # Using eval to safely evaluate the string representation of list of dicts
    # Note: If the column is already in list-dict format, you can skip the eval
    genre_list = eval(genre_list)
    # Extracting the 'name' key from each dictionary in the list
    genre_names = [genre['name'] for genre in genre_list]
    # Joining the genre names into a single string, separated by commas
    return ', '.join(genre_names)

# Applying the function to the 'genre' column and assigning the result to a new column
tmdb['Genre Names'] = tmdb['genres'].apply(extract_genre_names)

# Display the first few rows to verify the new column
tmdb.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,Genre Names
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction"
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Adventure, Fantasy, Action"
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"Action, Adventure, Crime"
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"Action, Crime, Drama, Thriller"
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"Action, Adventure, Science Fiction"

In [3]:
# Function to extract and join keyword names
def extract_keyword_names(keyword_list):
    # Using eval to safely evaluate the string representation of list of dicts
    # Note: If the column is already in list-dict format, skip the eval
    keyword_list = eval(keyword_list)
    # Extracting the 'name' key from each dictionary in the list
    keyword_names = [keyword['name'] for keyword in keyword_list]
    # Joining the keyword names into a single string, separated by commas
    return ', '.join(keyword_names)

# Applying the function to the 'keywords' column and assigning the result to a new column
tmdb['Keyword Names'] = tmdb['keywords'].apply(extract_keyword_names)

# Display the first few rows to verify the new column
tmdb.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,..."

In [4]:
columns_to_drop = ['genres', 'keywords', 'homepage','original_title','status','spoken_languages']

# Dropping columns
tmdb2 = tmdb.drop(columns=columns_to_drop)

tmdb2

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
0,237000000,19995,en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,Enter the World of Pandora.,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony..."
1,300000000,285,en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t..."
2,245000000,206647,en,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,A Plan No One Escapes,Spectre,6.3,4466,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6..."
3,250000000,49026,en,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,The Legend Ends,The Dark Knight Rises,7.6,9106,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id..."
4,260000000,49529,en,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"Lost in our world, found in another.",John Carter,6.1,2124,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,9367,es,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,"Action, Crime, Thriller","united statesâ€“mexico barrier, legs, arms, pape..."
4799,9000,72766,en,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,"Comedy, Romance",
4800,0,231617,en,"""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,NaN,"Signed, Sealed, Delivered",7.0,6,"Comedy, Drama, Romance, TV Movie","date, love at first sight, narration, investig..."
4801,0,126186,en,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,A New Yorker in Shanghai,Shanghai Calling,5.7,7,,
4802,0,25975,en,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,NaN,My Date with Drew,6.3,16,Documentary,"obsession, camcorder, crush, dream girl"

In [5]:
tmdb2.isna()

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4799,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4800,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4801,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4802,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [6]:
nan_values = tmdb2[tmdb2["release_date"].isna()]

# Display the rows with NaN values in the specified column
nan_values

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
4553,0,380097,en,1971 post civil rights San Francisco seemed li...,0.0,[],[],NaN,0,0.0,NaN,America Is Still the Place,0.0,0,,

In [7]:
nan_values2 = tmdb2[tmdb2["tagline"].isnull()]
nan_values2

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
10,270000000,1452,en,Superman returns to discover his 5-year absenc...,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-06-28,391081192,154.0,NaN,Superman Returns,5.4,1400,"Adventure, Fantasy, Action, Science Fiction","saving the world, dc comics, invulnerability, ..."
56,185000000,188927,en,The USS Enterprise crew explores the furthest ...,65.352913,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-07-07,343471816,122.0,NaN,Star Trek Beyond,6.6,2568,"Action, Adventure, Science Fiction","sequel, stranded, hatred, space opera"
66,175000000,14160,en,Carl Fredricksen spent his entire life dreamin...,92.201962,"[{""name"": ""Pixar Animation Studios"", ""id"": 3}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-05-13,735099082,96.0,NaN,Up,7.7,6870,"Animation, Comedy, Family, Adventure","age difference, central and south america, bal..."
78,175000000,278927,en,After a threat from the tiger Shere Khan force...,94.199316,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2016-04-07,966550600,106.0,NaN,The Jungle Book,6.7,2892,"Family, Adventure, Drama, Fantasy","based on novel, snake, wolf, elephant, tiger, ..."
128,150000000,13448,en,Harvard symbologist Robert Langdon investigate...,67.447636,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""IT"", ""name"": ""Italy""}, {""iso_...",2009-05-13,356613439,138.0,NaN,Angels & Demons,6.5,2129,"Thriller, Mystery","rome, vatican, based on novel, symbolism, chri..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4790,0,13898,fa,Various women struggle to function in the oppr...,1.193779,"[{""name"": ""Jafar Panahi Film Productions"", ""id...","[{""iso_3166_1"": ""IR"", ""name"": ""Iran""}]",2000-09-08,0,90.0,NaN,The Circle,6.6,17,"Drama, Foreign",
4794,0,286939,en,"It should have been just a normal day of sex, ...",0.166513,"[{""name"": ""Gold Lion Films"", ""id"": 37870}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-01-20,0,82.0,NaN,Sanctuary: Quite a Conundrum,0.0,0,"Thriller, Horror, Comedy",
4797,0,67238,en,"Adam, a security guard, travels from Californi...",0.022173,[],[],2005-03-12,0,80.0,NaN,Cavite,7.5,2,"Foreign, Thriller",
4800,0,231617,en,"""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,NaN,"Signed, Sealed, Delivered",7.0,6,"Comedy, Drama, Romance, TV Movie","date, love at first sight, narration, investig..."
4802,0,25975,en,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,NaN,My Date with Drew,6.3,16,Documentary,"obsession, camcorder, crush, dream girl"

In [8]:
nan_values3 = tmdb2[tmdb2["overview"].isnull() | (tmdb2["overview"] == 'NaN') | (tmdb2["overview"] == 'NA')]
nan_values3

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
2656,15000000,370980,it,NaN,0.738646,"[{""name"": ""Taodue Film"", ""id"": 45724}]","[{""iso_3166_1"": ""IT"", ""name"": ""Italy""}]",2015-12-03,0,NaN,NaN,Chiamatemi Francesco - Il Papa della gente,7.3,12,Drama,"pope, biography"
4140,2,459488,en,NaN,0.050625,"[{""name"": ""Eyeline Entertainment"", ""id"": 60343}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",2015-12-12,0,NaN,NaN,"To Be Frank, Sinatra at 100",0.0,0,Documentary,"music, actors, legendary perfomer, classic hol..."
4431,913000,292539,de,NaN,0.795698,[],[],2014-04-26,0,83.0,NaN,Food Chains,7.4,8,Documentary,

In [9]:
nan_values4 = tmdb2[tmdb2["Genre Names"].isnull() | (tmdb2["Genre Names"] == 'NaN') | (tmdb2["Genre Names"] == 'NA')]
nan_values4

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [10]:
nan_values5 = tmdb2[tmdb2["id"].isnull() | (tmdb2["id"] == 'NaN') | (tmdb2["id"] == 'NA')]
nan_values5

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [11]:
nan_values6 = tmdb2[tmdb2["Keyword Names"].isnull() | (tmdb2["Keyword Names"] == 'NaN') | (tmdb2["Keyword Names"] == 'NA')]
nan_values6

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [12]:
nan_values7 = tmdb2[tmdb2["original_language"].isnull() | (tmdb2["original_language"] == 'NaN') | (tmdb2["original_language"] == 'NA')]
nan_values7

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [13]:
nan_values8 = tmdb2[tmdb2["popularity"].isnull() | (tmdb2["popularity"] == 'NaN') | (tmdb2["popularity"] == 'NA')]
nan_values8

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [14]:
nan_values9 = tmdb2[tmdb2["production_companies"].isnull() | (tmdb2["production_companies"] == 'NaN') | (tmdb2["production_companies"] == 'NA')]
nan_values9

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [15]:
nan_values10 = tmdb2[tmdb2["production_countries"].isnull() | (tmdb2["production_countries"] == 'NaN') | (tmdb2["production_countries"] == 'NA')]
nan_values10

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [16]:
nan_values11 = tmdb2[tmdb2["runtime"].isnull() | (tmdb2["runtime"] == 'NaN') | (tmdb2["runtime"] == 'NA')]
nan_values11

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
2656,15000000,370980,it,NaN,0.738646,"[{""name"": ""Taodue Film"", ""id"": 45724}]","[{""iso_3166_1"": ""IT"", ""name"": ""Italy""}]",2015-12-03,0,NaN,NaN,Chiamatemi Francesco - Il Papa della gente,7.3,12,Drama,"pope, biography"
4140,2,459488,en,NaN,0.050625,"[{""name"": ""Eyeline Entertainment"", ""id"": 60343}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",2015-12-12,0,NaN,NaN,"To Be Frank, Sinatra at 100",0.0,0,Documentary,"music, actors, legendary perfomer, classic hol..."

In [17]:
nan_values12 = tmdb2[tmdb2["title"].isnull() | (tmdb2["title"] == 'NaN') | (tmdb2["title"] == 'NA')]
nan_values12

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [18]:
nan_values13 = tmdb2[tmdb2["vote_average"].isnull() | (tmdb2["vote_average"] == 'NaN') | (tmdb2["vote_average"] == 'NA')]
nan_values13

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [19]:
nan_values14 = tmdb2[tmdb2["vote_count"].isnull() | (tmdb2["vote_count"] == 'NaN') | (tmdb2["vote_count"] == 'NA')]
nan_values14

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [20]:
column_name = 'budget'  # Replace 'column_name' with the name of the column you want to check
column_type = tmdb2[column_name].dtype
print(f"The type of the '{column_name}' column is: {column_type}")

The type of the 'budget' column is: int64

In [21]:
# Select the column you want to fill 0 values
column_name = 'budget'  # Replace 'column_name' with the name of the column you want to fill

# Check if there are any 0 values in the column
print("Number of 0 values before replacement:", (tmdb2[column_name] == 0).sum())

# Calculate the mean excluding 0 values and round it to the nearest whole number
mean_without_zeros = round(tmdb2[tmdb2[column_name] != 0][column_name].mean())

# Replace 0 values with the rounded mean
tmdb2[column_name] = tmdb2[column_name].replace(0, mean_without_zeros)

# Check if there are any 0 values in the column after replacement
print("Number of 0 values after replacement:", (tmdb2[column_name] == 0).sum())

Number of 0 values before replacement: 1037
Number of 0 values after replacement: 0

In [22]:
# Select the column you want to fill 0 values
column_name = 'vote_count'  # Replace 'column_name' with the name of the column you want to fill

# Check if there are any 0 values in the column
print("Number of 0 values before replacement:", (tmdb2[column_name] == 0).sum())

# Calculate the mean excluding 0 values and round it to the nearest whole number
mean_without_zeros = round(tmdb2[tmdb2[column_name] != 0][column_name].mean())

# Replace 0 values with the rounded mean
tmdb2[column_name] = tmdb2[column_name].replace(0, mean_without_zeros)

# Check if there are any 0 values in the column after replacement
print("Number of 0 values after replacement:", (tmdb2[column_name] == 0).sum())

Number of 0 values before replacement: 62
Number of 0 values after replacement: 0

In [23]:
# Select the column you want to fill 0 values
column_name = 'vote_average'  # Replace 'column_name' with the name of the column you want to fill

# Check if there are any 0 values in the column
print("Number of 0 values before replacement:", (tmdb2[column_name] == 0).sum())

# Calculate the mean excluding 0 values and round it to the nearest whole number
mean_without_zeros = round(tmdb2[tmdb2[column_name] != 0][column_name].mean())

# Replace 0 values with the rounded mean
tmdb2[column_name] = tmdb2[column_name].replace(0, mean_without_zeros)

# Check if there are any 0 values in the column after replacement
print("Number of 0 values after replacement:", (tmdb2[column_name] == 0).sum())

Number of 0 values before replacement: 63
Number of 0 values after replacement: 0

In [24]:
# Select the column you want to fill 0 values
column_name = 'popularity'  # Replace 'column_name' with the name of the column you want to fill

# Check if there are any 0 values in the column
print("Number of 0 values before replacement:", (tmdb2[column_name] == 0).sum())

# Calculate the mean excluding 0 values and round it to the nearest whole number
mean_without_zeros = round(tmdb2[tmdb2[column_name] != 0][column_name].mean())

# Replace 0 values with the rounded mean
tmdb2[column_name] = tmdb2[column_name].replace(0, mean_without_zeros)

# Check if there are any 0 values in the column after replacement
print("Number of 0 values after replacement:", (tmdb2[column_name] == 0).sum())

Number of 0 values before replacement: 1
Number of 0 values after replacement: 0

In [25]:
# Select the column you want to fill 0 values
column_name = 'runtime'  # Replace 'column_name' with the name of the column you want to fill

# Check if there are any 0 values in the column
print("Number of 0 values before replacement:", (tmdb2[column_name] == 0).sum())

# Calculate the mean excluding 0 values and round it to the nearest whole number
mean_without_zeros = round(tmdb2[tmdb2[column_name] != 0][column_name].mean())

# Replace 0 values with the rounded mean
tmdb2[column_name] = tmdb2[column_name].replace(0, mean_without_zeros)

# Check if there are any 0 values in the column after replacement
print("Number of 0 values after replacement:", (tmdb2[column_name] == 0).sum())

Number of 0 values before replacement: 35
Number of 0 values after replacement: 0

In [26]:
# Mapping null values in 'tagline' with corresponding values from 'title'
tmdb2['tagline'] = tmdb2['tagline'].fillna(tmdb2['title'])
tmdb2

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
0,237000000,19995,en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,Enter the World of Pandora.,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony..."
1,300000000,285,en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t..."
2,245000000,206647,en,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,A Plan No One Escapes,Spectre,6.3,4466,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6..."
3,250000000,49026,en,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,The Legend Ends,The Dark Knight Rises,7.6,9106,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id..."
4,260000000,49529,en,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"Lost in our world, found in another.",John Carter,6.1,2124,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,9367,es,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,"Action, Crime, Thriller","united statesâ€“mexico barrier, legs, arms, pape..."
4799,9000,72766,en,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,"Comedy, Romance",
4800,37042838,231617,en,"""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"Signed, Sealed, Delivered","Signed, Sealed, Delivered",7.0,6,"Comedy, Drama, Romance, TV Movie","date, love at first sight, narration, investig..."
4801,37042838,126186,en,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,A New Yorker in Shanghai,Shanghai Calling,5.7,7,,
4802,37042838,25975,en,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,My Date with Drew,My Date with Drew,6.3,16,Documentary,"obsession, camcorder, crush, dream girl"

In [27]:
nan_values15 = tmdb2[tmdb2["tagline"].isnull()]
nan_values15

Empty DataFrame
Columns: [budget, id, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, tagline, title, vote_average, vote_count, Genre Names, Keyword Names]
Index: []

In [28]:
tmdb2 = tmdb2.dropna(subset=['overview'])
tmdb2

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
0,237000000,19995,en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,Enter the World of Pandora.,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony..."
1,300000000,285,en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t..."
2,245000000,206647,en,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,A Plan No One Escapes,Spectre,6.3,4466,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6..."
3,250000000,49026,en,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,The Legend Ends,The Dark Knight Rises,7.6,9106,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id..."
4,260000000,49529,en,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"Lost in our world, found in another.",John Carter,6.1,2124,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,9367,es,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,"Action, Crime, Thriller","united statesâ€“mexico barrier, legs, arms, pape..."
4799,9000,72766,en,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,"Comedy, Romance",
4800,37042838,231617,en,"""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"Signed, Sealed, Delivered","Signed, Sealed, Delivered",7.0,6,"Comedy, Drama, Romance, TV Movie","date, love at first sight, narration, investig..."
4801,37042838,126186,en,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,A New Yorker in Shanghai,Shanghai Calling,5.7,7,,
4802,37042838,25975,en,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,My Date with Drew,My Date with Drew,6.3,16,Documentary,"obsession, camcorder, crush, dream girl"

In [29]:
tmdb2 = tmdb2.dropna(subset=['release_date'])
tmdb2

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
0,237000000,19995,en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,Enter the World of Pandora.,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony..."
1,300000000,285,en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t..."
2,245000000,206647,en,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,A Plan No One Escapes,Spectre,6.3,4466,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6..."
3,250000000,49026,en,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,The Legend Ends,The Dark Knight Rises,7.6,9106,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id..."
4,260000000,49529,en,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"Lost in our world, found in another.",John Carter,6.1,2124,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,9367,es,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,"Action, Crime, Thriller","united statesâ€“mexico barrier, legs, arms, pape..."
4799,9000,72766,en,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,"Comedy, Romance",
4800,37042838,231617,en,"""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"Signed, Sealed, Delivered","Signed, Sealed, Delivered",7.0,6,"Comedy, Drama, Romance, TV Movie","date, love at first sight, narration, investig..."
4801,37042838,126186,en,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,A New Yorker in Shanghai,Shanghai Calling,5.7,7,,
4802,37042838,25975,en,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,My Date with Drew,My Date with Drew,6.3,16,Documentary,"obsession, camcorder, crush, dream girl"

In [30]:
output_file_path = 'no_null_vals2.csv'  # Specify the path for the new CSV file
tmdb2.to_csv(output_file_path, index=False)  # Set index=False to omit writing row indices

In [31]:
tmdb2

,budget,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,tagline,title,vote_average,vote_count,Genre Names,Keyword Names
0,237000000,19995,en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,Enter the World of Pandora.,Avatar,7.2,11800,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony..."
1,300000000,285,en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t..."
2,245000000,206647,en,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,A Plan No One Escapes,Spectre,6.3,4466,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6..."
3,250000000,49026,en,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,The Legend Ends,The Dark Knight Rises,7.6,9106,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id..."
4,260000000,49529,en,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"Lost in our world, found in another.",John Carter,6.1,2124,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,9367,es,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,"Action, Crime, Thriller","united statesâ€“mexico barrier, legs, arms, pape..."
4799,9000,72766,en,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,"Comedy, Romance",
4800,37042838,231617,en,"""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"Signed, Sealed, Delivered","Signed, Sealed, Delivered",7.0,6,"Comedy, Drama, Romance, TV Movie","date, love at first sight, narration, investig..."
4801,37042838,126186,en,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,A New Yorker in Shanghai,Shanghai Calling,5.7,7,,
4802,37042838,25975,en,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,My Date with Drew,My Date with Drew,6.3,16,Documentary,"obsession, camcorder, crush, dream girl"

In [32]:
tmdb2.columns

Index(['budget', 'id', 'original_language', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'tagline', 'title', 'vote_average', 'vote_count',
       'Genre Names', 'Keyword Names'],
      dtype='object')

In [33]:
"""
import pandas as pd
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

# Load your dataset
df = pd.read_csv("no_null_vals2.csv")

# Encode the 'Genre' column into numerical values
label_encoder = LabelEncoder()
df['GenreEncoded'] = label_encoder.fit_transform(df['Genre Names'])

# Preprocessing for Word2Vec
class TextCleaner(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_cleaned = X.apply(lambda x: x.split())  # Tokenization
        return X_cleaned

# Preprocessing for other features
preprocessor = ColumnTransformer(
    transformers=[
        ('origin', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore'))
        ]), ['Origin'])
    ])

# Word2Vec model
word2vec_model = Word2Vec(sentences=df['overview'].apply(lambda x: x.split()), vector_size=100, window=5, min_count=1, workers=4)

# Tokenize and pad sequences for neural network input
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['overview'])
sequences = tokenizer.texts_to_sequences(df['overview'])
padded_sequences = pad_sequences(sequences)

# Neural network model
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=100, input_length=padded_sequences.shape[1]))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(df['Genre Names'].unique()), activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, df['GenreEncoded'], test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Evaluate model accuracy
accuracy = model.evaluate(X_test, y_test, verbose=0)[1]
print(f"Model Accuracy: {accuracy:.2%}")

# Function to predict the genre for a new plot
def predict_genre_nn(new_plot):
    # Tokenize and pad the new plot
    new_sequence = tokenizer.texts_to_sequences([new_plot])
    new_padded_sequence = pad_sequences(new_sequence, maxlen=padded_sequences.shape[1])

    # Make the prediction
    prediction_probs = model.predict(new_padded_sequence)[0]
    predicted_genre_index = np.argmax(prediction_probs)
    predicted_genre = label_encoder.inverse_transform([predicted_genre_index])[0]

    # Print the confidence of each genre
    print("Confidence of Each Genre:")
    for genre_index, prob in enumerate(prediction_probs):
        genre = label_encoder.inverse_transform([genre_index])[0]
        print(f"{genre}: {prob:.2%}")

    return predicted_genre, prediction_probs[predicted_genre_index]

# Example usage
#new_plot = "In a future where time travel is a reality, scientist Emily Turner stumbles upon a groundbreaking discovery that could alter the course of history. As she races against a shadowy organization intent on controlling time, Emily, along with her colleagues David Anderson, Sophia Lee, and Michael Harris, embarks on a mind-bending journey through different eras. The sci-fi odyssey unfolds with paradoxes, futuristic landscapes, and unforeseen challenges. Will Emily and her team protect the fabric of time, or will they become pawns in a game that transcends the boundaries of space and existence."
#new_plot = " The Sevastopol, a next-generation Russian stealth submarine, employs an advanced AI, which is activated by a two-piece cruciform key. The AI deceives the crew into attacking a phantom target, only to be struck by their own torpedo, killing all aboard. IMF agent Ethan Hunt travels to the Empty Quarter of the Arabian Desert and successfully retrieves a key piece from Ilsa Faust, a disavowed MI6 agent, and also fakes her death to ensure she survives a bounty placed by an unknown source. Back in Washington, D.C., Ethan infiltrates a U.S. Intelligence Community briefing for Director of National Intelligence Denlinger discussing the AI, known as the Entity. CIA Director Eugene Kittridge states that the Entity achieved sentience and can manipulate cyberspace, allowing it to control global defense intelligence and financial networks. World powers compete to obtain the cruciform key to control the Entity, though the exact means of controlling it are unknown. Ethan reveals himself and converses with Kittridge, where he deduces that Kittridge placed Ilsas bounty and states his intention to destroy the Entity, knowing they would be considered rogue and are participating in a global race. Ethan and his IMF teammates Benji Dunn and Luther Stickell travel to Abu Dhabi International Airport to intercept the holder of the other key piece, while evading US agents. During the pursuit, the key piece is stolen by Grace, a professional thief, while Luther and Benji disarm a hoax nuclear device. Ethan suspects foul play after seeing Gabriel, a sadistic Entity liaison with ties to his pre-IMF past. Aborting the mission, the team scatters and Grace escapes to Rome. Grace is apprehended upon arrival, but Ethan rescues her from local authorities, US agents and Paris, an Entity operative. Grace escapes again, while Ethan meets up with Luther and Benji, with Ilsa rejoining them. With Benji and Luther providing support, Ethan and Ilsa follow Grace to Venice, where they infiltrate a party held by the arms dealer Alanna Mitsopolis.With the party masquerading as a brokerage set up by the Entity, all groups disclose their role in acquiring the complete key. Grace was hired by Alanna to steal the other key piece to produce the completed key, which will be sold to her buyer the next day on the Orient Express. Through the Entity, Gabriel proclaims that he will possess the completed key the next day and that either Ilsa or Grace will die. Ethan unsuccessfully attempts to dissuade Alanna from the sale, allowing Gabriel and Grace to escape. Ethan pursues Grace, but the Entity hacks into their communications and impersonates Benji, leading him into a fight with Paris, whom he spares. Concurrently, Gabriel incapacitates Grace and kills Ilsa, devastating Ethan, who vows to exact revenge. Grace agrees to impersonate Alanna and take the key during the sale. Luther leaves for an off-grid location to prevent interference from the Entity, advising Ethan to spare Gabriel to determine information about the Entity. On the train, Gabriel kills the engine crew and destroys the throttle and brake. With Paris, Gabriel meets Denlinger, who divulges information only he knows in an attempt to form an alliance between himself and the Entity.Originally an advanced cyber weapon developed by the US, the Entity went rogue following its deployment against the Sevastopol. The completed key unlocks a chamber inside the vessel containing the Entitys source code, allowing it to be destroyed or controlled. Gabriel subsequently kills Denlinger and tries to kill Paris as the Entity determined she would betray them after Ethan spared her life. Impersonating Alanna, Grace brings the key to Kittridge, revealed to be the buyer, and negotiates a $100 million sale alongside protection for herself, but pickpockets the key from Kittridge after cancelling the transfer. Ethan parachutes into the train to save Grace, but Gabriel acquires the key. Ethan and Gabriel fight atop the train, but Gabriel escapes and detonates a bridge ahead. Grace and Ethan detach the locomotive from the rest of the train, saving the passengers. Paris rescues both from falling and manages to tell Ethan about the key's connection to the Sevastopol before losing consciousness. Grace informs Kittridge of her desire to join the IMF. Ethan flees the wreckage by paraglider with the completed key, which he took from Gabriel during the fight, and rendezvous with Benji to continue the mission of finding the Sevastopol and destroying the Entity."
#new_plot = "Ahana, Neil and Imaad are three friends in their 20s trying to find meaning in the digital age. They lean on each other as they navigate complexities of relationships and self-discovery."
#new_plot = "In 1934, Cadet Sam Manekshaw is amongst the first batch of gentleman cadets to be trained at the Indian Military Academy, Dehradun; amongst his batchmates is his junior-rival, Tikka Khan. Graduating from the academy that year, he is posted as a second lieutenant to the 12th Frontier Force Regiment, Ferozpur. Soon after his appointment, he meets Siloo Bode, whom he later marries. In 1942, during the Second World War, Manekshaw, promoted to the acting rank of major, is sent with the regiment to participate in the Burma campaign. During the Battle of Sittang Bridge, he is wounded in action but survives and is awarded the Military Cross for gallantry.In 1947, amidst the partition of the British Indian Army, Major Manekshaw is approached to join the Pakistan Army by his colleague, Yahya Khan; he chooses the Indian Army instead. Upon independence, discord emanates between the two countries over the sovereignty of Kashmir. In October 1947, Pakistan launches its military campaign to capture the region. In response, Indian prime minister Jawaharlal Nehru and home minister Vallabhbhai Patel dispatch Manekshaw and V. P. Menon to Kashmir; they succeed in securing the accession of Kashmir to India. India counter-attacks, but the war concludes in a stalemate.In 1959, Manekshaw, now a major general and Commandant of the Defence Services Staff College, Wellington, is approached by defence minister V. K. Krishna Menon and Chief of General Staff Lt. Gen. Brij Mohan Kaul of his opinion on the Chief of Army Staff (COAS) Gen. K. S. Thimayya. Manekshaw, interpreting their actions as political interference, rebuffs them. However, Kaul conspires to stop Manekshaw's upcoming promotion by orchestrating a court-martial on the basis of impropriety; nevertheless, but Manekshaw is exonerated by his superiors.In 1962, the Sino-Indian War erupts, leading to the army being trounced by the Chinese; Kaul resigns while Nehru dismisses Menon. On the advice of Indira Gandhi, Nehru has Manekshaw promoted to lieutenant-general and assigns him as commanding officer of the IV Corps, Tezpur. He proposes an advance, but Nehru, forlorn from defeat, refuses; Indira intercedes in Manekshaw's favour. By 1963, Manekshaw manages to re-rally his troops in the North-East Frontier Agency. In 1964, Nehru dies, and Manekshaw is promoted as general commanding officer of the Eastern Command; two years later, Indira is appointed prime minister. Between 1965 and 1967, Manekshaw involves himself in the anti-insurgency operations against the Mizo National Front, for which he earns the Padma Bhushan.In 1969, with discord amongst the Bengalis in East Pakistan rising, Yahya, now a general, is made Pakistan's president; elsewhere, Manekshaw is appointed as the Indian Army's next COAS and promoted to general as well. In 1970, the East Pakistan-based Awami League sweep Pakistan's general elections, however Yahya refuses to cede power to them, resulting in anti-government protests across Pakistan. In response, Yahya authorises Tikka, now a lieutenant-general, to initiate Operation Searchlight â€“ a massive anti-Bengali pogrom, which he executes with ruthless efficiency. Considering the situation, Indira favours war, but Manekshaw opposes it, highlighting the army's hindrances; she agrees to wait. The U.S. warns Indira against war, but she rebuffs them. The army is mobilised and begins training the Mukti Bahini.On 3 December 1971, Pakistan strikes first, launching pre-emptive attacks on Indian territory. India immediately responds with counter-attacks in Pakistan's western and eastern sectors. The opposing armies witness profound clashes, with Pakistan bearing numerous casualties on land, sea and air in both sectors. By 16 December, the Pakistani troops in the east, overwhelmed, surrender to the Eastern Command â€“ ending the war. The conclusion cedes a political triumph to Indira while Yahya resigns from the humiliation of defeat. With Manekshaw's retirement approaching, Indira has him to be promoted to the rank of field-marshal in recognition of his wartime leadership; he proudly retires in January 1973."
new_plot = "Five years after the events of Don, the European drug cartel bosses meet to discuss Don, who is jeopardizing their business by undercutting their prices. They decide that he must die. Living in Thailand for the last five years, Don goes to a remote settlement to pick up a shipment of cocaine. He gets cornered by his own associates who reveal that they were offered a deal by the Europeans to have their cocaine from Asia be open for sale in Europe. Don makes his way out by killing all his men and destroying the entire settlement. He returns to Malaysia, surrendering to Detective Malik and Roma, who has joined Interpol. He is sentenced to death and sent to prison, where he meets old rival Vardhaan.Vardhaan tries to exact revenge on Don for having him imprisoned but agrees to work together with him when Don offers him an opportunity to escape. Don and Vardhaan eventually break out by poisoning the other inmates. In Zurich, Don meets trusted companion Ayesha, and they retrieve a tape from a secret locker whose key was under Vardhaan's possession. It shows J. K. Diwan, vice-president of the Euro-printing DZB (Deutsche Zentral Bank) bribing Singhania to kill James Werden, the original choice for the bankâ€™s president so that Diwan's superior, Fabian Kohl, would get the post. Singhania was killed by Vardhaan five years earlier. Don blackmails Diwan into giving him the bank's blueprints so he can steal the printing plates. Diwan gives him fake blueprints and hires Abdul Jabbar, a deadly assassin.Don escapes and bribes Jabbar to work for him instead. With no other choice, Diwan gives him the original blueprints. Roma and Malik arrive in Berlin and unsuccessfully interrogate Diwan while Don and his team execute a bank robbery. After stealing the printing plates, Don is betrayed by Vardhaan and Jabbar but, having anticipated this, escapes. Another team member, Sameer, calls the police on Don and he is arrested. Don blackmails Diwan into giving him German immunity in exchange for erasing the evidence of him being involved in the murder of James Warden. He negotiates with the Berlin Police and Interpol over surrendering the plates and a disc containing details of the European underworld in exchange for the safety of the hostages and defusing the bombs in the bank.Don and Roma reach Vardhaan after bloody combat with his thugs and find themselves in a standoff. Though ordered by Vardhaan and Jabbar - and Don himself - Roma is unable to kill Don and is shot by Jabbar in response; she still has feelings for him, though he killed her brother and his fiancÃ©e five years earlier, and also does not want to do it illegally. Don subdues Vardhaan and kills Jabbar. He obtains his immunity papers and surrenders the plates and the disc as per the bargain, while also getting Roma to an ambulance. Later, Don detonates a bomb planted in Diwan's car, killing Diwan and seemingly destroying the plates he had taken.In a final scene, it is revealed that Don still has the currency plates; the ones which the police believe was destroyed in the explosion were fake. Sameer was actually loyal to Don; informing the police was part of the plan. The disc Don turned over actually contains the names of the European drug cartel. Having been exposed, Kohl is shortly arrested, and the DZB is forced to replace him. Don becomes king of the European underworld."
predicted_genre, confidence = predict_genre_nn(new_plot)

print(f"Predicted Genre: {predicted_genre} (Confidence: {confidence:.2%})")
"""

'\nimport pandas as pd\nfrom gensim.models import Word2Vec\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.base import BaseEstimator, TransformerMixin\nfrom tensorflow.keras.models import Sequential\nfrom tensorflow.keras.layers import Embedding, Flatten, Dense, Dropout\nfrom tensorflow.keras.preprocessing.text import Tokenizer\nfrom tensorflow.keras.preprocessing.sequence import pad_sequences\nimport numpy as np\n\n# Load your dataset\ndf = pd.read_csv("no_null_vals2.csv")\n\n# Encode the \'Genre\' column into numerical values\nlabel_encoder = LabelEncoder()\ndf[\'GenreEncoded\'] = label_encoder.fit_transform(df[\'Genre Names\'])\n\n# Preprocessing for Word2Vec\nclass TextCleaner(BaseEstimator, TransformerMixin):\n    def fit(self, X, y=None):\n        return self\n\n    def transform(self, X):\n        X_cleaned = X.apply(lambda x: x.split())  # Tokenization\n        return X_cleaned\n\n# Preprocessing for other features\npreprocessor = ColumnTransformer(\n    transformers=[\n        (\'origin\', Pipeline(steps=[\n            (\'imputer\', SimpleImputer(strategy=\'most_frequent\')),\n            (\'onehot\', OneHotEncoder(handle_unknown=\'ignore\'))\n        ]), [\'Origin\'])\n    ])\n\n# Word2Vec model\nword2vec_model = Word2Vec(sentences=df[\'overview\'].apply(lambda x: x.split()), vector_size=100, window=5, min_count=1, workers=4)\n\n# Tokenize and pad sequences for neural network input\ntokenizer = Tokenizer()\ntokenizer.fit_on_texts(df[\'overview\'])\nsequences = tokenizer.texts_to_sequences(df[\'overview\'])\npadded_sequences = pad_sequences(sequences)\n\n# Neural network model\nmodel = Sequential()\nmodel.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=100, input_length=padded_sequences.shape[1]))\nmodel.add(Flatten())\nmodel.add(Dense(128, activation=\'relu\'))\nmodel.add(Dropout(0.5))\nmodel.add(Dense(64, activation=\'relu\'))\nmodel.add(Dropout(0.5))\nmodel.add(Dense(len(df[\'Genre Names\'].unique()), activation=\'softmax\'))\n\n# Compile the model\nmodel.compile(optimizer=\'adam\', loss=\'sparse_categorical_crossentropy\', metrics=[\'accuracy\'])\n\n# Train-test split\nX_train, X_test, y_train, y_test = train_test_split(padded_sequences, df[\'GenreEncoded\'], test_size=0.2, random_state=42)\n\n# Train the model\nmodel.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))\n\n# Evaluate model accuracy\naccuracy = model.evaluate(X_test, y_test, verbose=0)[1]\nprint(f"Model Accuracy: {accuracy:.2%}")\n\n# Function to predict the genre for a new plot\ndef predict_genre_nn(new_plot):\n    # Tokenize and pad the new plot\n    new_sequence = tokenizer.texts_to_sequences([new_plot])\n    new_padded_sequence = pad_sequences(new_sequence, maxlen=padded_sequences.shape[1])\n\n    # Make the prediction\n    prediction_probs = model.predict(new_padded_sequence)[0]\n    predicted_genre_index = np.argmax(prediction_probs)\n    predicted_genre = label_encoder.inverse_transform([predicted_genre_index])[0]\n\n    # Print the confidence of each genre\n    print("Confidence of Each Genre:")\n    for genre_index, prob in enumerate(prediction_probs):\n        genre = label_encoder.inverse_transform([genre_index])[0]\n        print(f"{genre}: {prob:.2%}")\n\n    return predicted_genre, prediction_probs[predicted_genre_index]\n\n# Example usage\n#new_plot = "In a future where time travel is a reality, scientist Emily Turner stumbles upon a groundbreaking discovery that could alter the course of history. As she races against a shadowy organization intent on controlling time, Emily, along with her colleagues David Anderson, Sophia Lee, and Michael Harris, embarks on a mind-bending journey through different eras. The sci-fi odyssey unfolds with paradoxes, futuristic landscapes, and unforeseen challenges. Will Emily and her team protect the fabric of time, or will they become pawns in a game that transcends the boundaries of space and existence."\n#new_plot = " The Sevastopol, a next-generation Russian stealth submarine, employs an advanced AI, which is activated by a two-piece cruciform key. The AI deceives the crew into attacking a phantom target, only to be struck by their own torpedo, killing all aboard. IMF agent Ethan Hunt travels to the Empty Quarter of the Arabian Desert and successfully retrieves a key piece from Ilsa Faust, a disavowed MI6 agent, and also fakes her death to ensure she survives a bounty placed by an unknown source. Back in Washington, D.C., Ethan infiltrates a U.S. Intelligence Community briefing for Director of National Intelligence Denlinger discussing the AI, known as the Entity. CIA Director Eugene Kittridge states that the Entity achieved sentience and can manipulate cyberspace, allowing it to control global defense intelligence and financial networks. World powers compete to obtain the cruciform key to control the Entity, though the exact means of controlling it are unknown. Ethan reveals himself and converses with Kittridge, where he deduces that Kittridge placed Ilsas bounty and states his intention to destroy the Entity, knowing they would be considered rogue and are participating in a global race. Ethan and his IMF teammates Benji Dunn and Luther Stickell travel to Abu Dhabi International Airport to intercept the holder of the other key piece, while evading US agents. During the pursuit, the key piece is stolen by Grace, a professional thief, while Luther and Benji disarm a hoax nuclear device. Ethan suspects foul play after seeing Gabriel, a sadistic Entity liaison with ties to his pre-IMF past. Aborting the mission, the team scatters and Grace escapes to Rome. Grace is apprehended upon arrival, but Ethan rescues her from local authorities, US agents and Paris, an Entity operative. Grace escapes again, while Ethan meets up with Luther and Benji, with Ilsa rejoining them. With Benji and Luther providing support, Ethan and Ilsa follow Grace to Venice, where they infiltrate a party held by the arms dealer Alanna Mitsopolis.With the party masquerading as a brokerage set up by the Entity, all groups disclose their role in acquiring the complete key. Grace was hired by Alanna to steal the other key piece to produce the completed key, which will be sold to her buyer the next day on the Orient Express. Through the Entity, Gabriel proclaims that he will possess the completed key the next day and that either Ilsa or Grace will die. Ethan unsuccessfully attempts to dissuade Alanna from the sale, allowing Gabriel and Grace to escape. Ethan pursues Grace, but the Entity hacks into their communications and impersonates Benji, leading him into a fight with Paris, whom he spares. Concurrently, Gabriel incapacitates Grace and kills Ilsa, devastating Ethan, who vows to exact revenge. Grace agrees to impersonate Alanna and take the key during the sale. Luther leaves for an off-grid location to prevent interference from the Entity, advising Ethan to spare Gabriel to determine information about the Entity. On the train, Gabriel kills the engine crew and destroys the throttle and brake. With Paris, Gabriel meets Denlinger, who divulges information only he knows in an attempt to form an alliance between himself and the Entity.Originally an advanced cyber weapon developed by the US, the Entity went rogue following its deployment against the Sevastopol. The completed key unlocks a chamber inside the vessel containing the Entitys source code, allowing it to be destroyed or controlled. Gabriel subsequently kills Denlinger and tries to kill Paris as the Entity determined she would betray them after Ethan spared her life. Impersonating Alanna, Grace brings the key to Kittridge, revealed to be the buyer, and negotiates a $100 million sale alongside protection for herself, but pickpockets the key from Kittridge after cancelling the transfer. Ethan parachutes into the train to save Grace, but Gabriel acquires the key. Ethan and Gabriel fight atop the train, but Gabriel escapes and detonates a bridge ahead. Grace and Ethan detach the locomotive from the rest of the train, saving the passengers. Paris rescues both from falling and manages to tell Ethan about the key\'s connection to the Sevastopol before losing consciousness. Grace informs Kittridge of her desire to join the IMF. Ethan flees the wreckage by paraglider with the completed key, which he took from Gabriel during the fight, and rendezvous with Benji to continue the mission of finding the Sevastopol and destroying the Entity."\n#new_plot = "Ahana, Neil and Imaad are three friends in their 20s trying to find meaning in the digital age. They lean on each other as they navigate complexities of relationships and self-discovery."\n#new_plot = "In 1934, Cadet Sam Manekshaw is amongst the first batch of gentleman cadets to be trained at the Indian Military Academy, Dehradun; amongst his batchmates is his junior-rival, Tikka Khan. Graduating from the academy that year, he is posted as a second lieutenant to the 12th Frontier Force Regiment, Ferozpur. Soon after his appointment, he meets Siloo Bode, whom he later marries. In 1942, during the Second World War, Manekshaw, promoted to the acting rank of major, is sent with the regiment to participate in the Burma campaign. During the Battle of Sittang Bridge, he is wounded in action but survives and is awarded the Military Cross for gallantry.In 1947, amidst the partition of the British Indian Army, Major Manekshaw is approached to join the Pakistan Army by his colleague, Yahya Khan; he chooses the Indian Army instead. Upon independence, discord emanates between the two countries over the sovereignty of Kashmir. In October 1947, Pakistan launches its military campaign to capture the region. In response, Indian prime minister Jawaharlal Nehru and home minister Vallabhbhai Patel dispatch Manekshaw and V. P. Menon to Kashmir; they succeed in securing the accession of Kashmir to India. India counter-attacks, but the war concludes in a stalemate.In 1959, Manekshaw, now a major general and Commandant of the Defence Services Staff College, Wellington, is approached by defence minister V. K. Krishna Menon and Chief of General Staff Lt. Gen. Brij Mohan Kaul of his opinion on the Chief of Army Staff (COAS) Gen. K. S. Thimayya. Manekshaw, interpreting their actions as political interference, rebuffs them. However, Kaul conspires to stop Manekshaw\'s upcoming promotion by orchestrating a court-martial on the basis of impropriety; nevertheless, but Manekshaw is exonerated by his superiors.In 1962, the Sino-Indian War erupts, leading to the army being trounced by the Chinese; Kaul resigns while Nehru dismisses Menon. On the advice of Indira Gandhi, Nehru has Manekshaw promoted to lieutenant-general and assigns him as commanding officer of the IV Corps, Tezpur. He proposes an advance, but Nehru, forlorn from defeat, refuses; Indira intercedes in Manekshaw\'s favour. By 1963, Manekshaw manages to re-rally his troops in the North-East Frontier Agency. In 1964, Nehru dies, and Manekshaw is promoted as general commanding officer of the Eastern Command; two years later, Indira is appointed prime minister. Between 1965 and 1967, Manekshaw involves himself in the anti-insurgency operations against the Mizo National Front, for which he earns the Padma Bhushan.In 1969, with discord amongst the Bengalis in East Pakistan rising, Yahya, now a general, is made Pakistan\'s president; elsewhere, Manekshaw is appointed as the Indian Army\'s next COAS and promoted to general as well. In 1970, the East Pakistan-based Awami League sweep Pakistan\'s general elections, however Yahya refuses to cede power to them, resulting in anti-government protests across Pakistan. In response, Yahya authorises Tikka, now a lieutenant-general, to initiate Operation Searchlight â€“ a massive anti-Bengali pogrom, which he executes with ruthless efficiency. Considering the situation, Indira favours war, but Manekshaw opposes it, highlighting the army\'s hindrances; she agrees to wait. The U.S. warns Indira against war, but she rebuffs them. The army is mobilised and begins training the Mukti Bahini.On 3 December 1971, Pakistan strikes first, launching pre-emptive attacks on Indian territory. India immediately responds with counter-attacks in Pakistan\'s western and eastern sectors. The opposing armies witness profound clashes, with Pakistan bearing numerous casualties on land, sea and air in both sectors. By 16 December, the Pakistani troops in the east, overwhelmed, surrender to the Eastern Command â€“ ending the war. The conclusion cedes a political triumph to Indira while Yahya resigns from the humiliation of defeat. With Manekshaw\'s retirement approaching, Indira has him to be promoted to the rank of field-marshal in recognition of his wartime leadership; he proudly retires in January 1973."\nnew_plot = "Five years after the events of Don, the European drug cartel bosses meet to discuss Don, who is jeopardizing their business by undercutting their prices. They decide that he must die. Living in Thailand for the last five years, Don goes to a remote settlement to pick up a shipment of cocaine. He gets cornered by his own associates who reveal that they were offered a deal by the Europeans to have their cocaine from Asia be open for sale in Europe. Don makes his way out by killing all his men and destroying the entire settlement. He returns to Malaysia, surrendering to Detective Malik and Roma, who has joined Interpol. He is sentenced to death and sent to prison, where he meets old rival Vardhaan.Vardhaan tries to exact revenge on Don for having him imprisoned but agrees to work together with him when Don offers him an opportunity to escape. Don and Vardhaan eventually break out by poisoning the other inmates. In Zurich, Don meets trusted companion Ayesha, and they retrieve a tape from a secret locker whose key was under Vardhaan\'s possession. It shows J. K. Diwan, vice-president of the Euro-printing DZB (Deutsche Zentral Bank) bribing Singhania to kill James Werden, the original choice for the bankâ€™s president so that Diwan\'s superior, Fabian Kohl, would get the post. Singhania was killed by Vardhaan five years earlier. Don blackmails Diwan into giving him the bank\'s blueprints so he can steal the printing plates. Diwan gives him fake blueprints and hires Abdul Jabbar, a deadly assassin.Don escapes and bribes Jabbar to work for him instead. With no other choice, Diwan gives him the original blueprints. Roma and Malik arrive in Berlin and unsuccessfully interrogate Diwan while Don and his team execute a bank robbery. After stealing the printing plates, Don is betrayed by Vardhaan and Jabbar but, having anticipated this, escapes. Another team member, Sameer, calls the police on Don and he is arrested. Don blackmails Diwan into giving him German immunity in exchange for erasing the evidence of him being involved in the murder of James Warden. He negotiates with the Berlin Police and Interpol over surrendering the plates and a disc containing details of the European underworld in exchange for the safety of the hostages and defusing the bombs in the bank.Don and Roma reach Vardhaan after bloody combat with his thugs and find themselves in a standoff. Though ordered by Vardhaan and Jabbar - and Don himself - Roma is unable to kill Don and is shot by Jabbar in response; she still has feelings for him, though he killed her brother and his fiancÃ©e five years earlier, and also does not want to do it illegally. Don subdues Vardhaan and kills Jabbar. He obtains his immunity papers and surrenders the plates and the disc as per the bargain, while also getting Roma to an ambulance. Later, Don detonates a bomb planted in Diwan\'s car, killing Diwan and seemingly destroying the plates he had taken.In a final scene, it is revealed that Don still has the currency plates; the ones which the police believe was destroyed in the explosion were fake. Sameer was actually loyal to Don; informing the police was part of the plan. The disc Don turned over actually contains the names of the European drug cartel. Having been exposed, Kohl is shortly arrested, and the DZB is forced to replace him. Don becomes king of the European underworld."\npredicted_genre, confidence = predict_genre_nn(new_plot)\n\nprint(f"Predicted Genre: {predicted_genre} (Confidence: {confidence:.2%})")\n'

In [34]:
"""
import pandas as pd
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

# Load your dataset
df = pd.read_csv("no_null_vals2.csv")

# Encode the 'Genre' column into numerical values
label_encoder = LabelEncoder()
df['GenreEncoded'] = label_encoder.fit_transform(df['Genre Names'])

# Preprocessing for Word2Vec
class TextCleaner(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_cleaned = X.apply(lambda x: x.split())  # Tokenization
        return X_cleaned

# Preprocessing for other features
preprocessor = ColumnTransformer(
    transformers=[
        ('origin', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore'))
        ]), ['Origin'])
    ])

# Word2Vec model
word2vec_model = Word2Vec(sentences=df['overview'].apply(lambda x: x.split()), vector_size=100, window=5, min_count=1, workers=4)

# Tokenize and pad sequences for neural network input
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['overview'])
sequences = tokenizer.texts_to_sequences(df['overview'])
padded_sequences = pad_sequences(sequences)

# Neural network model
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=100, input_length=padded_sequences.shape[1]))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(df['Genre Names'].unique()), activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, df['GenreEncoded'], test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=128, validation_data=(X_test, y_test))

# Evaluate model accuracy
accuracy = model.evaluate(X_test, y_test, verbose=0)[1]
print(f"Model Accuracy: {accuracy:.2%}")

# Function to predict the genre for a new plot
def predict_genre_nn(new_plot):
    # Tokenize and pad the new plot
    new_sequence = tokenizer.texts_to_sequences([new_plot])
    new_padded_sequence = pad_sequences(new_sequence, maxlen=padded_sequences.shape[1])

    # Make the prediction
    prediction_probs = model.predict(new_padded_sequence)[0]
    predicted_genre_index = np.argmax(prediction_probs)
    predicted_genre = label_encoder.inverse_transform([predicted_genre_index])[0]

    # Print the confidence of each genre
    print("Confidence of Each Genre:")
    for genre_index, prob in enumerate(prediction_probs):
        genre = label_encoder.inverse_transform([genre_index])[0]
        print(f"{genre}: {prob:.2%}")

    return predicted_genre, prediction_probs[predicted_genre_index]

# Example usage
#new_plot = "In a future where time travel is a reality, scientist Emily Turner stumbles upon a groundbreaking discovery that could alter the course of history. As she races against a shadowy organization intent on controlling time, Emily, along with her colleagues David Anderson, Sophia Lee, and Michael Harris, embarks on a mind-bending journey through different eras. The sci-fi odyssey unfolds with paradoxes, futuristic landscapes, and unforeseen challenges. Will Emily and her team protect the fabric of time, or will they become pawns in a game that transcends the boundaries of space and existence."
#new_plot = " The Sevastopol, a next-generation Russian stealth submarine, employs an advanced AI, which is activated by a two-piece cruciform key. The AI deceives the crew into attacking a phantom target, only to be struck by their own torpedo, killing all aboard. IMF agent Ethan Hunt travels to the Empty Quarter of the Arabian Desert and successfully retrieves a key piece from Ilsa Faust, a disavowed MI6 agent, and also fakes her death to ensure she survives a bounty placed by an unknown source. Back in Washington, D.C., Ethan infiltrates a U.S. Intelligence Community briefing for Director of National Intelligence Denlinger discussing the AI, known as the Entity. CIA Director Eugene Kittridge states that the Entity achieved sentience and can manipulate cyberspace, allowing it to control global defense intelligence and financial networks. World powers compete to obtain the cruciform key to control the Entity, though the exact means of controlling it are unknown. Ethan reveals himself and converses with Kittridge, where he deduces that Kittridge placed Ilsas bounty and states his intention to destroy the Entity, knowing they would be considered rogue and are participating in a global race. Ethan and his IMF teammates Benji Dunn and Luther Stickell travel to Abu Dhabi International Airport to intercept the holder of the other key piece, while evading US agents. During the pursuit, the key piece is stolen by Grace, a professional thief, while Luther and Benji disarm a hoax nuclear device. Ethan suspects foul play after seeing Gabriel, a sadistic Entity liaison with ties to his pre-IMF past. Aborting the mission, the team scatters and Grace escapes to Rome. Grace is apprehended upon arrival, but Ethan rescues her from local authorities, US agents and Paris, an Entity operative. Grace escapes again, while Ethan meets up with Luther and Benji, with Ilsa rejoining them. With Benji and Luther providing support, Ethan and Ilsa follow Grace to Venice, where they infiltrate a party held by the arms dealer Alanna Mitsopolis.With the party masquerading as a brokerage set up by the Entity, all groups disclose their role in acquiring the complete key. Grace was hired by Alanna to steal the other key piece to produce the completed key, which will be sold to her buyer the next day on the Orient Express. Through the Entity, Gabriel proclaims that he will possess the completed key the next day and that either Ilsa or Grace will die. Ethan unsuccessfully attempts to dissuade Alanna from the sale, allowing Gabriel and Grace to escape. Ethan pursues Grace, but the Entity hacks into their communications and impersonates Benji, leading him into a fight with Paris, whom he spares. Concurrently, Gabriel incapacitates Grace and kills Ilsa, devastating Ethan, who vows to exact revenge. Grace agrees to impersonate Alanna and take the key during the sale. Luther leaves for an off-grid location to prevent interference from the Entity, advising Ethan to spare Gabriel to determine information about the Entity. On the train, Gabriel kills the engine crew and destroys the throttle and brake. With Paris, Gabriel meets Denlinger, who divulges information only he knows in an attempt to form an alliance between himself and the Entity.Originally an advanced cyber weapon developed by the US, the Entity went rogue following its deployment against the Sevastopol. The completed key unlocks a chamber inside the vessel containing the Entitys source code, allowing it to be destroyed or controlled. Gabriel subsequently kills Denlinger and tries to kill Paris as the Entity determined she would betray them after Ethan spared her life. Impersonating Alanna, Grace brings the key to Kittridge, revealed to be the buyer, and negotiates a $100 million sale alongside protection for herself, but pickpockets the key from Kittridge after cancelling the transfer. Ethan parachutes into the train to save Grace, but Gabriel acquires the key. Ethan and Gabriel fight atop the train, but Gabriel escapes and detonates a bridge ahead. Grace and Ethan detach the locomotive from the rest of the train, saving the passengers. Paris rescues both from falling and manages to tell Ethan about the key's connection to the Sevastopol before losing consciousness. Grace informs Kittridge of her desire to join the IMF. Ethan flees the wreckage by paraglider with the completed key, which he took from Gabriel during the fight, and rendezvous with Benji to continue the mission of finding the Sevastopol and destroying the Entity."
#new_plot = "Ahana, Neil and Imaad are three friends in their 20s trying to find meaning in the digital age. They lean on each other as they navigate complexities of relationships and self-discovery."
#new_plot = "Five years after the events of Don, the European drug cartel bosses meet to discuss Don, who is jeopardizing their business by undercutting their prices. They decide that he must die. Living in Thailand for the last five years, Don goes to a remote settlement to pick up a shipment of cocaine. He gets cornered by his own associates who reveal that they were offered a deal by the Europeans to have their cocaine from Asia be open for sale in Europe. Don makes his way out by killing all his men and destroying the entire settlement. He returns to Malaysia, surrendering to Detective Malik and Roma, who has joined Interpol. He is sentenced to death and sent to prison, where he meets old rival Vardhaan.Vardhaan tries to exact revenge on Don for having him imprisoned but agrees to work together with him when Don offers him an opportunity to escape. Don and Vardhaan eventually break out by poisoning the other inmates. In Zurich, Don meets trusted companion Ayesha, and they retrieve a tape from a secret locker whose key was under Vardhaan's possession. It shows J. K. Diwan, vice-president of the Euro-printing DZB (Deutsche Zentral Bank) bribing Singhania to kill James Werden, the original choice for the bankâ€™s president so that Diwan's superior, Fabian Kohl, would get the post. Singhania was killed by Vardhaan five years earlier. Don blackmails Diwan into giving him the bank's blueprints so he can steal the printing plates. Diwan gives him fake blueprints and hires Abdul Jabbar, a deadly assassin.Don escapes and bribes Jabbar to work for him instead. With no other choice, Diwan gives him the original blueprints. Roma and Malik arrive in Berlin and unsuccessfully interrogate Diwan while Don and his team execute a bank robbery. After stealing the printing plates, Don is betrayed by Vardhaan and Jabbar but, having anticipated this, escapes. Another team member, Sameer, calls the police on Don and he is arrested. Don blackmails Diwan into giving him German immunity in exchange for erasing the evidence of him being involved in the murder of James Warden. He negotiates with the Berlin Police and Interpol over surrendering the plates and a disc containing details of the European underworld in exchange for the safety of the hostages and defusing the bombs in the bank.Don and Roma reach Vardhaan after bloody combat with his thugs and find themselves in a standoff. Though ordered by Vardhaan and Jabbar - and Don himself - Roma is unable to kill Don and is shot by Jabbar in response; she still has feelings for him, though he killed her brother and his fiancÃ©e five years earlier, and also does not want to do it illegally. Don subdues Vardhaan and kills Jabbar. He obtains his immunity papers and surrenders the plates and the disc as per the bargain, while also getting Roma to an ambulance. Later, Don detonates a bomb planted in Diwan's car, killing Diwan and seemingly destroying the plates he had taken.In a final scene, it is revealed that Don still has the currency plates; the ones which the police believe was destroyed in the explosion were fake. Sameer was actually loyal to Don; informing the police was part of the plan. The disc Don turned over actually contains the names of the European drug cartel. Having been exposed, Kohl is shortly arrested, and the DZB is forced to replace him. Don becomes king of the European underworld."
new_plot = "The unnamed Narrator is an insomniac automobile recall specialist dissatisfied with his job and lifestyle. He attends support groups for problems such as alcoholism and cancer as a substitute for therapy. His efforts are disrupted when another impostor, Marla Singer, joins the same groups. Viewing her as a mirror to his own deceit, he arranges for them to attend different sessions, to which she reluctantly agrees.On a return flight from work, the Narrator meets a soap salesman, Tyler Durden, who criticizes his consumerist lifestyle. After an explosion destroys the Narrator's apartment, he moves into Tyler's decrepit house. They become friends and start an underground fight club in a bar basement. Tyler also saves Marla from an overdose, initiating a sexual relationship between them, while the Narrator remains cold to her.The Narrator quits his job, blackmails his boss for funds, and grows Fight Club, attracting new members, including his cancer support group friend, Bob. Tyler morphs the club into Project Mayhem, committing acts of vandalism intended to disrupt the social order. Feeling sidelined, the Narrator confronts Tyler, who admits to orchestrating the explosion in the Narrator's apartment and then goes missing. When the police kill Bob during a mission, the Narrator tries to dismantle Project Mayhem. Discovering its nationwide reach and being called Tyler Durden by Marla and members, he realizes he and Tyler are split personalities.Learning that Tyler plans to erase debt records by blowing up the skyscrapers of consumer credit companies, the Narrator unsuccessfully warns Marla and goes to the police, some of whom are also Project Mayhem members. He attempts to disarm the explosives, but Tyler attacks him. Accepting that he is Tyler, he shoots himself in the mouth, killing Tyler, while the bullet non-fatally passes through the Narrator's cheek. Marla arrives, and the two hold hands as they watch the targeted buildings collapse."
#new_plot = "A gang of robbers on motorbikes, led by Kabir, carry out robberies in Banks and other public places in Mumbai, causing chaos to the police. Assistant Commissioner of Police Jai Dixit, a no-nonsense police officer, is assigned to the case.Jai seeks the help of a local bike dealer and racer, Ali Akbar Fateh Khan and creates a plan to trap the gang, though it fails. Kabir taunts Jai, claiming that he wouldn't even be able to catch him even if he was right in front of him. He is proven correct when Jai's failure causes him to part ways with Ali.Kabir lures Ali into his gang as a substitute for Rohit, a member of Kabir's gang who was killed by Jai. Ali falls in love with Sheena, another member in the gang. The gang plan their next and final heist in Goa before parting ways. The gang plan to rob a casino on New Year's Eve. Kabir and his gang successfully rob the casino, however Kabir realizes that Jai led him into a trap. It is revealed that Ali was working with Jai the entire time, and a fight ensues.Kabir manages to escape and goes back to the gang's truck, where Ali has kept Sheena hostage. Kabir confronts and beats up Ali for his betrayal, however Jai arrives and saves Ali. Kabir and his gang, except for Sheena, flee and Jai and Ali go after Kabir. Jai and Ali eliminate the gang except for Kabir, who attempts to escape, but is cornered by Jai and Ali. Rather than letting Jai arrest him, Kabir decides to take his own life by riding his bike over the edge of a cliff. The film ends with Jai and Ali arguing with one another, in a friendly way."
#new_plot = "In 1934, Cadet Sam Manekshaw is amongst the first batch of gentleman cadets to be trained at the Indian Military Academy, Dehradun; amongst his batchmates is his junior-rival, Tikka Khan. Graduating from the academy that year, he is posted as a second lieutenant to the 12th Frontier Force Regiment, Ferozpur. Soon after his appointment, he meets Siloo Bode, whom he later marries. In 1942, during the Second World War, Manekshaw, promoted to the acting rank of major, is sent with the regiment to participate in the Burma campaign. During the Battle of Sittang Bridge, he is wounded in action but survives and is awarded the Military Cross for gallantry.In 1947, amidst the partition of the British Indian Army, Major Manekshaw is approached to join the Pakistan Army by his colleague, Yahya Khan; he chooses the Indian Army instead. Upon independence, discord emanates between the two countries over the sovereignty of Kashmir. In October 1947, Pakistan launches its military campaign to capture the region. In response, Indian prime minister Jawaharlal Nehru and home minister Vallabhbhai Patel dispatch Manekshaw and V. P. Menon to Kashmir; they succeed in securing the accession of Kashmir to India. India counter-attacks, but the war concludes in a stalemate.In 1959, Manekshaw, now a major general and Commandant of the Defence Services Staff College, Wellington, is approached by defence minister V. K. Krishna Menon and Chief of General Staff Lt. Gen. Brij Mohan Kaul of his opinion on the Chief of Army Staff (COAS) Gen. K. S. Thimayya. Manekshaw, interpreting their actions as political interference, rebuffs them. However, Kaul conspires to stop Manekshaw's upcoming promotion by orchestrating a court-martial on the basis of impropriety; nevertheless, but Manekshaw is exonerated by his superiors.In 1962, the Sino-Indian War erupts, leading to the army being trounced by the Chinese; Kaul resigns while Nehru dismisses Menon. On the advice of Indira Gandhi, Nehru has Manekshaw promoted to lieutenant-general and assigns him as commanding officer of the IV Corps, Tezpur. He proposes an advance, but Nehru, forlorn from defeat, refuses; Indira intercedes in Manekshaw's favour. By 1963, Manekshaw manages to re-rally his troops in the North-East Frontier Agency. In 1964, Nehru dies, and Manekshaw is promoted as general commanding officer of the Eastern Command; two years later, Indira is appointed prime minister. Between 1965 and 1967, Manekshaw involves himself in the anti-insurgency operations against the Mizo National Front, for which he earns the Padma Bhushan.In 1969, with discord amongst the Bengalis in East Pakistan rising, Yahya, now a general, is made Pakistan's president; elsewhere, Manekshaw is appointed as the Indian Army's next COAS and promoted to general as well. In 1970, the East Pakistan-based Awami League sweep Pakistan's general elections, however Yahya refuses to cede power to them, resulting in anti-government protests across Pakistan. In response, Yahya authorises Tikka, now a lieutenant-general, to initiate Operation Searchlight â€“ a massive anti-Bengali pogrom, which he executes with ruthless efficiency. Considering the situation, Indira favours war, but Manekshaw opposes it, highlighting the army's hindrances; she agrees to wait. The U.S. warns Indira against war, but she rebuffs them. The army is mobilised and begins training the Mukti Bahini.On 3 December 1971, Pakistan strikes first, launching pre-emptive attacks on Indian territory. India immediately responds with counter-attacks in Pakistan's western and eastern sectors. The opposing armies witness profound clashes, with Pakistan bearing numerous casualties on land, sea and air in both sectors. By 16 December, the Pakistani troops in the east, overwhelmed, surrender to the Eastern Command â€“ ending the war. The conclusion cedes a political triumph to Indira while Yahya resigns from the humiliation of defeat. With Manekshaw's retirement approaching, Indira has him to be promoted to the rank of field-marshal in recognition of his wartime leadership; he proudly retires in January 1973."
predicted_genre, confidence = predict_genre_nn(new_plot)

print(f"Predicted Genre: {predicted_genre} (Confidence: {confidence:.2%})")
"""

'\nimport pandas as pd\nfrom gensim.models import Word2Vec\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.base import BaseEstimator, TransformerMixin\nfrom tensorflow.keras.models import Sequential\nfrom tensorflow.keras.layers import Embedding, Flatten, Dense, Dropout\nfrom tensorflow.keras.preprocessing.text import Tokenizer\nfrom tensorflow.keras.preprocessing.sequence import pad_sequences\nimport numpy as np\n\n# Load your dataset\ndf = pd.read_csv("no_null_vals2.csv")\n\n# Encode the \'Genre\' column into numerical values\nlabel_encoder = LabelEncoder()\ndf[\'GenreEncoded\'] = label_encoder.fit_transform(df[\'Genre Names\'])\n\n# Preprocessing for Word2Vec\nclass TextCleaner(BaseEstimator, TransformerMixin):\n    def fit(self, X, y=None):\n        return self\n\n    def transform(self, X):\n        X_cleaned = X.apply(lambda x: x.split())  # Tokenization\n        return X_cleaned\n\n# Preprocessing for other features\npreprocessor = ColumnTransformer(\n    transformers=[\n        (\'origin\', Pipeline(steps=[\n            (\'imputer\', SimpleImputer(strategy=\'most_frequent\')),\n            (\'onehot\', OneHotEncoder(handle_unknown=\'ignore\'))\n        ]), [\'Origin\'])\n    ])\n\n# Word2Vec model\nword2vec_model = Word2Vec(sentences=df[\'overview\'].apply(lambda x: x.split()), vector_size=100, window=5, min_count=1, workers=4)\n\n# Tokenize and pad sequences for neural network input\ntokenizer = Tokenizer()\ntokenizer.fit_on_texts(df[\'overview\'])\nsequences = tokenizer.texts_to_sequences(df[\'overview\'])\npadded_sequences = pad_sequences(sequences)\n\n# Neural network model\nmodel = Sequential()\nmodel.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=100, input_length=padded_sequences.shape[1]))\nmodel.add(Flatten())\nmodel.add(Dense(128, activation=\'relu\'))\nmodel.add(Dropout(0.5))\nmodel.add(Dense(64, activation=\'relu\'))\nmodel.add(Dropout(0.5))\nmodel.add(Dense(len(df[\'Genre Names\'].unique()), activation=\'softmax\'))\n\n# Compile the model\nmodel.compile(optimizer=\'adam\', loss=\'sparse_categorical_crossentropy\', metrics=[\'accuracy\'])\n\n# Train-test split\nX_train, X_test, y_train, y_test = train_test_split(padded_sequences, df[\'GenreEncoded\'], test_size=0.2, random_state=42)\n\n# Train the model\nmodel.fit(X_train, y_train, epochs=100, batch_size=128, validation_data=(X_test, y_test))\n\n# Evaluate model accuracy\naccuracy = model.evaluate(X_test, y_test, verbose=0)[1]\nprint(f"Model Accuracy: {accuracy:.2%}")\n\n# Function to predict the genre for a new plot\ndef predict_genre_nn(new_plot):\n    # Tokenize and pad the new plot\n    new_sequence = tokenizer.texts_to_sequences([new_plot])\n    new_padded_sequence = pad_sequences(new_sequence, maxlen=padded_sequences.shape[1])\n\n    # Make the prediction\n    prediction_probs = model.predict(new_padded_sequence)[0]\n    predicted_genre_index = np.argmax(prediction_probs)\n    predicted_genre = label_encoder.inverse_transform([predicted_genre_index])[0]\n\n    # Print the confidence of each genre\n    print("Confidence of Each Genre:")\n    for genre_index, prob in enumerate(prediction_probs):\n        genre = label_encoder.inverse_transform([genre_index])[0]\n        print(f"{genre}: {prob:.2%}")\n\n    return predicted_genre, prediction_probs[predicted_genre_index]\n\n# Example usage\n#new_plot = "In a future where time travel is a reality, scientist Emily Turner stumbles upon a groundbreaking discovery that could alter the course of history. As she races against a shadowy organization intent on controlling time, Emily, along with her colleagues David Anderson, Sophia Lee, and Michael Harris, embarks on a mind-bending journey through different eras. The sci-fi odyssey unfolds with paradoxes, futuristic landscapes, and unforeseen challenges. Will Emily and her team protect the fabric of time, or will they become pawns in a game that transcends the boundaries of space and existence."\n#new_plot = " The Sevastopol, a next-generation Russian stealth submarine, employs an advanced AI, which is activated by a two-piece cruciform key. The AI deceives the crew into attacking a phantom target, only to be struck by their own torpedo, killing all aboard. IMF agent Ethan Hunt travels to the Empty Quarter of the Arabian Desert and successfully retrieves a key piece from Ilsa Faust, a disavowed MI6 agent, and also fakes her death to ensure she survives a bounty placed by an unknown source. Back in Washington, D.C., Ethan infiltrates a U.S. Intelligence Community briefing for Director of National Intelligence Denlinger discussing the AI, known as the Entity. CIA Director Eugene Kittridge states that the Entity achieved sentience and can manipulate cyberspace, allowing it to control global defense intelligence and financial networks. World powers compete to obtain the cruciform key to control the Entity, though the exact means of controlling it are unknown. Ethan reveals himself and converses with Kittridge, where he deduces that Kittridge placed Ilsas bounty and states his intention to destroy the Entity, knowing they would be considered rogue and are participating in a global race. Ethan and his IMF teammates Benji Dunn and Luther Stickell travel to Abu Dhabi International Airport to intercept the holder of the other key piece, while evading US agents. During the pursuit, the key piece is stolen by Grace, a professional thief, while Luther and Benji disarm a hoax nuclear device. Ethan suspects foul play after seeing Gabriel, a sadistic Entity liaison with ties to his pre-IMF past. Aborting the mission, the team scatters and Grace escapes to Rome. Grace is apprehended upon arrival, but Ethan rescues her from local authorities, US agents and Paris, an Entity operative. Grace escapes again, while Ethan meets up with Luther and Benji, with Ilsa rejoining them. With Benji and Luther providing support, Ethan and Ilsa follow Grace to Venice, where they infiltrate a party held by the arms dealer Alanna Mitsopolis.With the party masquerading as a brokerage set up by the Entity, all groups disclose their role in acquiring the complete key. Grace was hired by Alanna to steal the other key piece to produce the completed key, which will be sold to her buyer the next day on the Orient Express. Through the Entity, Gabriel proclaims that he will possess the completed key the next day and that either Ilsa or Grace will die. Ethan unsuccessfully attempts to dissuade Alanna from the sale, allowing Gabriel and Grace to escape. Ethan pursues Grace, but the Entity hacks into their communications and impersonates Benji, leading him into a fight with Paris, whom he spares. Concurrently, Gabriel incapacitates Grace and kills Ilsa, devastating Ethan, who vows to exact revenge. Grace agrees to impersonate Alanna and take the key during the sale. Luther leaves for an off-grid location to prevent interference from the Entity, advising Ethan to spare Gabriel to determine information about the Entity. On the train, Gabriel kills the engine crew and destroys the throttle and brake. With Paris, Gabriel meets Denlinger, who divulges information only he knows in an attempt to form an alliance between himself and the Entity.Originally an advanced cyber weapon developed by the US, the Entity went rogue following its deployment against the Sevastopol. The completed key unlocks a chamber inside the vessel containing the Entitys source code, allowing it to be destroyed or controlled. Gabriel subsequently kills Denlinger and tries to kill Paris as the Entity determined she would betray them after Ethan spared her life. Impersonating Alanna, Grace brings the key to Kittridge, revealed to be the buyer, and negotiates a $100 million sale alongside protection for herself, but pickpockets the key from Kittridge after cancelling the transfer. Ethan parachutes into the train to save Grace, but Gabriel acquires the key. Ethan and Gabriel fight atop the train, but Gabriel escapes and detonates a bridge ahead. Grace and Ethan detach the locomotive from the rest of the train, saving the passengers. Paris rescues both from falling and manages to tell Ethan about the key\'s connection to the Sevastopol before losing consciousness. Grace informs Kittridge of her desire to join the IMF. Ethan flees the wreckage by paraglider with the completed key, which he took from Gabriel during the fight, and rendezvous with Benji to continue the mission of finding the Sevastopol and destroying the Entity."\n#new_plot = "Ahana, Neil and Imaad are three friends in their 20s trying to find meaning in the digital age. They lean on each other as they navigate complexities of relationships and self-discovery."\n#new_plot = "Five years after the events of Don, the European drug cartel bosses meet to discuss Don, who is jeopardizing their business by undercutting their prices. They decide that he must die. Living in Thailand for the last five years, Don goes to a remote settlement to pick up a shipment of cocaine. He gets cornered by his own associates who reveal that they were offered a deal by the Europeans to have their cocaine from Asia be open for sale in Europe. Don makes his way out by killing all his men and destroying the entire settlement. He returns to Malaysia, surrendering to Detective Malik and Roma, who has joined Interpol. He is sentenced to death and sent to prison, where he meets old rival Vardhaan.Vardhaan tries to exact revenge on Don for having him imprisoned but agrees to work together with him when Don offers him an opportunity to escape. Don and Vardhaan eventually break out by poisoning the other inmates. In Zurich, Don meets trusted companion Ayesha, and they retrieve a tape from a secret locker whose key was under Vardhaan\'s possession. It shows J. K. Diwan, vice-president of the Euro-printing DZB (Deutsche Zentral Bank) bribing Singhania to kill James Werden, the original choice for the bankâ€™s president so that Diwan\'s superior, Fabian Kohl, would get the post. Singhania was killed by Vardhaan five years earlier. Don blackmails Diwan into giving him the bank\'s blueprints so he can steal the printing plates. Diwan gives him fake blueprints and hires Abdul Jabbar, a deadly assassin.Don escapes and bribes Jabbar to work for him instead. With no other choice, Diwan gives him the original blueprints. Roma and Malik arrive in Berlin and unsuccessfully interrogate Diwan while Don and his team execute a bank robbery. After stealing the printing plates, Don is betrayed by Vardhaan and Jabbar but, having anticipated this, escapes. Another team member, Sameer, calls the police on Don and he is arrested. Don blackmails Diwan into giving him German immunity in exchange for erasing the evidence of him being involved in the murder of James Warden. He negotiates with the Berlin Police and Interpol over surrendering the plates and a disc containing details of the European underworld in exchange for the safety of the hostages and defusing the bombs in the bank.Don and Roma reach Vardhaan after bloody combat with his thugs and find themselves in a standoff. Though ordered by Vardhaan and Jabbar - and Don himself - Roma is unable to kill Don and is shot by Jabbar in response; she still has feelings for him, though he killed her brother and his fiancÃ©e five years earlier, and also does not want to do it illegally. Don subdues Vardhaan and kills Jabbar. He obtains his immunity papers and surrenders the plates and the disc as per the bargain, while also getting Roma to an ambulance. Later, Don detonates a bomb planted in Diwan\'s car, killing Diwan and seemingly destroying the plates he had taken.In a final scene, it is revealed that Don still has the currency plates; the ones which the police believe was destroyed in the explosion were fake. Sameer was actually loyal to Don; informing the police was part of the plan. The disc Don turned over actually contains the names of the European drug cartel. Having been exposed, Kohl is shortly arrested, and the DZB is forced to replace him. Don becomes king of the European underworld."\nnew_plot = "The unnamed Narrator is an insomniac automobile recall specialist dissatisfied with his job and lifestyle. He attends support groups for problems such as alcoholism and cancer as a substitute for therapy. His efforts are disrupted when another impostor, Marla Singer, joins the same groups. Viewing her as a mirror to his own deceit, he arranges for them to attend different sessions, to which she reluctantly agrees.On a return flight from work, the Narrator meets a soap salesman, Tyler Durden, who criticizes his consumerist lifestyle. After an explosion destroys the Narrator\'s apartment, he moves into Tyler\'s decrepit house. They become friends and start an underground fight club in a bar basement. Tyler also saves Marla from an overdose, initiating a sexual relationship between them, while the Narrator remains cold to her.The Narrator quits his job, blackmails his boss for funds, and grows Fight Club, attracting new members, including his cancer support group friend, Bob. Tyler morphs the club into Project Mayhem, committing acts of vandalism intended to disrupt the social order. Feeling sidelined, the Narrator confronts Tyler, who admits to orchestrating the explosion in the Narrator\'s apartment and then goes missing. When the police kill Bob during a mission, the Narrator tries to dismantle Project Mayhem. Discovering its nationwide reach and being called Tyler Durden by Marla and members, he realizes he and Tyler are split personalities.Learning that Tyler plans to erase debt records by blowing up the skyscrapers of consumer credit companies, the Narrator unsuccessfully warns Marla and goes to the police, some of whom are also Project Mayhem members. He attempts to disarm the explosives, but Tyler attacks him. Accepting that he is Tyler, he shoots himself in the mouth, killing Tyler, while the bullet non-fatally passes through the Narrator\'s cheek. Marla arrives, and the two hold hands as they watch the targeted buildings collapse."\n#new_plot = "A gang of robbers on motorbikes, led by Kabir, carry out robberies in Banks and other public places in Mumbai, causing chaos to the police. Assistant Commissioner of Police Jai Dixit, a no-nonsense police officer, is assigned to the case.Jai seeks the help of a local bike dealer and racer, Ali Akbar Fateh Khan and creates a plan to trap the gang, though it fails. Kabir taunts Jai, claiming that he wouldn\'t even be able to catch him even if he was right in front of him. He is proven correct when Jai\'s failure causes him to part ways with Ali.Kabir lures Ali into his gang as a substitute for Rohit, a member of Kabir\'s gang who was killed by Jai. Ali falls in love with Sheena, another member in the gang. The gang plan their next and final heist in Goa before parting ways. The gang plan to rob a casino on New Year\'s Eve. Kabir and his gang successfully rob the casino, however Kabir realizes that Jai led him into a trap. It is revealed that Ali was working with Jai the entire time, and a fight ensues.Kabir manages to escape and goes back to the gang\'s truck, where Ali has kept Sheena hostage. Kabir confronts and beats up Ali for his betrayal, however Jai arrives and saves Ali. Kabir and his gang, except for Sheena, flee and Jai and Ali go after Kabir. Jai and Ali eliminate the gang except for Kabir, who attempts to escape, but is cornered by Jai and Ali. Rather than letting Jai arrest him, Kabir decides to take his own life by riding his bike over the edge of a cliff. The film ends with Jai and Ali arguing with one another, in a friendly way."\n#new_plot = "In 1934, Cadet Sam Manekshaw is amongst the first batch of gentleman cadets to be trained at the Indian Military Academy, Dehradun; amongst his batchmates is his junior-rival, Tikka Khan. Graduating from the academy that year, he is posted as a second lieutenant to the 12th Frontier Force Regiment, Ferozpur. Soon after his appointment, he meets Siloo Bode, whom he later marries. In 1942, during the Second World War, Manekshaw, promoted to the acting rank of major, is sent with the regiment to participate in the Burma campaign. During the Battle of Sittang Bridge, he is wounded in action but survives and is awarded the Military Cross for gallantry.In 1947, amidst the partition of the British Indian Army, Major Manekshaw is approached to join the Pakistan Army by his colleague, Yahya Khan; he chooses the Indian Army instead. Upon independence, discord emanates between the two countries over the sovereignty of Kashmir. In October 1947, Pakistan launches its military campaign to capture the region. In response, Indian prime minister Jawaharlal Nehru and home minister Vallabhbhai Patel dispatch Manekshaw and V. P. Menon to Kashmir; they succeed in securing the accession of Kashmir to India. India counter-attacks, but the war concludes in a stalemate.In 1959, Manekshaw, now a major general and Commandant of the Defence Services Staff College, Wellington, is approached by defence minister V. K. Krishna Menon and Chief of General Staff Lt. Gen. Brij Mohan Kaul of his opinion on the Chief of Army Staff (COAS) Gen. K. S. Thimayya. Manekshaw, interpreting their actions as political interference, rebuffs them. However, Kaul conspires to stop Manekshaw\'s upcoming promotion by orchestrating a court-martial on the basis of impropriety; nevertheless, but Manekshaw is exonerated by his superiors.In 1962, the Sino-Indian War erupts, leading to the army being trounced by the Chinese; Kaul resigns while Nehru dismisses Menon. On the advice of Indira Gandhi, Nehru has Manekshaw promoted to lieutenant-general and assigns him as commanding officer of the IV Corps, Tezpur. He proposes an advance, but Nehru, forlorn from defeat, refuses; Indira intercedes in Manekshaw\'s favour. By 1963, Manekshaw manages to re-rally his troops in the North-East Frontier Agency. In 1964, Nehru dies, and Manekshaw is promoted as general commanding officer of the Eastern Command; two years later, Indira is appointed prime minister. Between 1965 and 1967, Manekshaw involves himself in the anti-insurgency operations against the Mizo National Front, for which he earns the Padma Bhushan.In 1969, with discord amongst the Bengalis in East Pakistan rising, Yahya, now a general, is made Pakistan\'s president; elsewhere, Manekshaw is appointed as the Indian Army\'s next COAS and promoted to general as well. In 1970, the East Pakistan-based Awami League sweep Pakistan\'s general elections, however Yahya refuses to cede power to them, resulting in anti-government protests across Pakistan. In response, Yahya authorises Tikka, now a lieutenant-general, to initiate Operation Searchlight â€“ a massive anti-Bengali pogrom, which he executes with ruthless efficiency. Considering the situation, Indira favours war, but Manekshaw opposes it, highlighting the army\'s hindrances; she agrees to wait. The U.S. warns Indira against war, but she rebuffs them. The army is mobilised and begins training the Mukti Bahini.On 3 December 1971, Pakistan strikes first, launching pre-emptive attacks on Indian territory. India immediately responds with counter-attacks in Pakistan\'s western and eastern sectors. The opposing armies witness profound clashes, with Pakistan bearing numerous casualties on land, sea and air in both sectors. By 16 December, the Pakistani troops in the east, overwhelmed, surrender to the Eastern Command â€“ ending the war. The conclusion cedes a political triumph to Indira while Yahya resigns from the humiliation of defeat. With Manekshaw\'s retirement approaching, Indira has him to be promoted to the rank of field-marshal in recognition of his wartime leadership; he proudly retires in Ja

In [35]:
import pandas as pd
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import tensorflow as tf

# List all physical devices TensorFlow can access
physical_devices = tf.config.list_physical_devices()

# Print information about available devices
print("Available devices:")
for device in physical_devices:
    print(device)

# Specifically checking for GPU availability
if any("GPU" in str(device.device_type) for device in physical_devices):
    print("Using Mac GPU via TensorFlow Metal plugin.")
else:
    print("GPU not available, using CPU instead.")

# Rest of your code follows...
# Load your dataset
df = pd.read_csv("no_null_vals2.csv")

# Encode the 'Genre' column into numerical values
label_encoder = LabelEncoder()
df['GenreEncoded'] = label_encoder.fit_transform(df['Genre Names'])

# Preprocessing for Word2Vec
class TextCleaner(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_cleaned = X.apply(lambda x: x.split())  # Tokenization
        return X_cleaned

# Preprocessing for other features
preprocessor = ColumnTransformer(
    transformers=[
        ('origin', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore'))
        ]), ['Origin'])
    ])

# Word2Vec model
word2vec_model = Word2Vec(sentences=df['overview'].apply(lambda x: x.split()), vector_size=100, window=5, min_count=1, workers=4)

# Tokenize and pad sequences for neural network input
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['overview'])
sequences = tokenizer.texts_to_sequences(df['overview'])
padded_sequences = pad_sequences(sequences)

# Neural network model
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=100, input_length=padded_sequences.shape[1]))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(df['Genre Names'].unique()), activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, df['GenreEncoded'], test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

# Evaluate model accuracy
accuracy = model.evaluate(X_test, y_test, verbose=0)[1]
print(f"Model Accuracy: {accuracy:.2%}")

# Function to predict the genre for a new plot
def predict_genre_nn(new_plot):
    # Tokenize and pad the new plot
    new_sequence = tokenizer.texts_to_sequences([new_plot])
    new_padded_sequence = pad_sequences(new_sequence, maxlen=padded_sequences.shape[1])

    # Make the prediction
    prediction_probs = model.predict(new_padded_sequence)[0]
    predicted_genre_index = np.argmax(prediction_probs)
    predicted_genre = label_encoder.inverse_transform([predicted_genre_index])[0]

    # Print the confidence of each genre
    print("Confidence of Each Genre:")
    for genre_index, prob in enumerate(prediction_probs):
        genre = label_encoder.inverse_transform([genre_index])[0]
        print(f"{genre}: {prob:.2%}")

    return predicted_genre, prediction_probs[predicted_genre_index]


new_plot = "In 1944 Nazi-occupied Poland, 14-year-old Erik Lehnsherr is separated from his parents upon entering the Auschwitz concentration camp. While attempting to reach them, he causes a set of metal gates to bend toward him because of his mutant ability to generate magnetic fields, but is knocked out by guards.In the not-too-distant future, U.S. Senator Robert Kelly attempts to pass a Mutant Registration Act in Congress, which would force mutants to reveal their identities and abilities. Nearby, Telepathic mutant Charles Xavier sees Lehnsherr, who now goes by the name Magneto, in attendance and is concerned with how he will respond to the Registration Act.In Meridian, Mississippi, 17-year-old Marie accidentally puts her boyfriend into a coma after kissing him, because of her mutant ability to absorb the power and life force of others. Adopting the name Rogue, she flees to Alberta and meets Logan, also known as Wolverine, a mutant with superhuman healing abilities and metal claws that protrude from between his knuckles. Sabretooth, a member of Magneto's Brotherhood of Mutants, attacks them on the road, but two members of Xavier's X-Men, Cyclops and Storm, save them. Wolverine and Rogue are brought to Xavier's school for mutants in Westchester County, New York. Believing that Magneto is interested in capturing Logan, Xavier asks him to stay while he investigates the matter. Meanwhile, Rogue enrolls in the school as a new pupil and develops a crush on cryokinetic mutant Bobby Drake.Brotherhood members Toad and Mystique abduct Senator Kelly, bringing him to their hideout on the uncharted island of Genosha. Magneto uses Kelly as a test subject for a machine powered by his magnetic abilities that generates a field of radiation, which induces mutations in normal humans. Taking advantage of his newfound mutation, Kelly later escapes. Rogue visits Wolverine during the night while he is having a nightmare. Startled, he accidentally stabs her, but she manages to absorb his healing ability and recover. Mystique, disguised as Drake, later convinces Rogue that Xavier is angry with her and that she must leave the school. Xavier uses his mutant-locating machine Cerebro to find Rogue at a train station, and the X-Men go to retrieve her. Meanwhile, Mystique enters Cerebro and sabotages it.Having left ahead of Storm and Cyclops, Wolverine finds Rogue on a train and convinces her to return. Before they can leave, Magneto arrives, incapacitates Logan and subdues Rogue, revealing it was her whom he wants rather than Wolverine. Although Xavier attempts to stop him by mentally controlling Sabretooth, he is forced to release his hold when Magneto threatens the police who have converged on the station, allowing the Brotherhood to escape with Rogue.Kelly arrives at the school, and Xavier reads his mind to learn about Magneto's machine. Realizing the strain of powering it nearly killed him, the X-Men deduce he intends to transfer his powers to Rogue and use her to power it at the cost of her life. Kelly's body rejects his mutation, and his body dissolves into liquid. Xavier attempts to locate Rogue using Cerebro, but Mystique's sabotage incapacitates him, and he falls into a coma. Fellow telekinetic and telepath Jean Grey fixes Cerebro and uses it, learning that the Brotherhood plans to place their machine on Liberty Island and use it to mutate the world leaders meeting at a summit on nearby Ellis Island. The X-Men scale the Statue of Liberty, battling and overpowering the Brotherhood while Magneto transfers his powers to Rogue and activates the machine. As Wolverine confronts and distracts Magneto, Cyclops blasts him away, allowing Logan to destroy the machine. He transfers his powers to Rogue, rejuvenating her while incapacitating himself.Xavier and Wolverine recover from their comas. The group also learns that Mystique escaped the island battle and is impersonating Kelly. Xavier gives Wolverine a lead to his past at an abandoned military installation in Canada before visiting Magneto, now imprisoned in a complex constructed of plastic. Magneto warns him that he intends to escape one day and continue the fight; Xavier replies that he will always be there to stop him."
predicted_genre, confidence = predict_genre_nn(new_plot)

print(f"Predicted Genre: {predicted_genre} (Confidence: {confidence:.2%})")

Available devices:
PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
GPU not available, using CPU instead.
Epoch 1/100
60/60 [==============================] - 2s 23ms/step - loss: 6.4934 - accuracy: 0.0466 - val_loss: 5.8745 - val_accuracy: 0.0865
Epoch 2/100
60/60 [==============================] - 1s 19ms/step - loss: 5.8767 - accuracy: 0.0630 - val_loss: 5.9144 - val_accuracy: 0.0865
Epoch 3/100
60/60 [==============================] - 1s 18ms/step - loss: 5.5731 - accuracy: 0.0677 - val_loss: 5.8343 - val_accuracy: 0.0865
Epoch 4/100
60/60 [==============================] - 1s 20ms/step - loss: 5.2042 - accuracy: 0.0732 - val_loss: 5.9046 - val_accuracy: 0.0885
Epoch 5/100
60/60 [==============================] - 1s 21ms/step - loss: 5.0778 - accuracy: 0.0703 - val_loss: 6.0595 - val_accuracy: 0.0865
Epoch 6/100
60/60 [==============================] - 1s 16ms/step - loss: 4.9974 - accuracy: 0.0643 - val_loss: 6.1426 - val_accuracy: 0.0875
Epoch 7/100
60/60 [==============================] - 1s 15ms/step - loss: 4.9149 - accuracy: 0.0714 - val_loss: 6.3245 - val_accuracy: 0.0875
Epoch 8/100
60/60 [==============================] - 1s 16ms/step - loss: 4.8518 - accuracy: 0.0737 - val_loss: 6.2122 - val_accuracy: 0.0854
Epoch 9/100
60/60 [==============================] - 1s 15ms/step - loss: 4.7632 - accuracy: 0.0818 - val_loss: 6.5045 - val_accuracy: 0.0812
Epoch 10/100
60/60 [==============================] - 1s 15ms/step - loss: 4.6410 - accuracy: 0.1029 - val_loss: 6.5178 - val_accuracy: 0.0802
Epoch 11/100
60/60 [==============================] - 1s 14ms/step - loss: 4.4752 - accuracy: 0.1245 - val_loss: 6.4909 - val_accuracy: 0.0760
Epoch 12/100
60/60 [==============================] - 1s 14ms/step - loss: 4.2883 - accuracy: 0.1602 - val_loss: 6.7637 - val_accuracy: 0.0635
Epoch 13/100
60/60 [==============================] - 1s 16ms/step - loss: 4.0925 - accuracy: 0.2118 - val_loss: 6.6417 - val_accuracy: 0.0500
Epoch 14/100
60/60 [==============================] - 1s 17ms/step - loss: 3.8450 - accuracy: 0.2613 - val_loss: 6.7825 - val_accuracy: 0.0500
Epoch 15/100
60/60 [==============================] - 1s 15ms/step - loss: 3.6504 - accuracy: 0.2933 - val_loss: 6.9783 - val_accuracy: 0.0448
Epoch 16/100
60/60 [==============================] - 1s 15ms/step - loss: 3.4265 - accuracy: 0.3407 - val_loss: 7.0686 - val_accuracy: 0.0458
Epoch 17/100
60/60 [==============================] - 1s 15ms/step - loss: 3.2284 - accuracy: 0.3754 - val_loss: 7.4032 - val_accuracy: 0.0427
Epoch 18/100
60/60 [==============================] - 1s 15ms/step - loss: 3.0992 - accuracy: 0.4006 - val_loss: 7.3886 - val_accuracy: 0.0323
Epoch 19/100
60/60 [==============================] - 1s 15ms/step - loss: 2.9980 - accuracy: 0.4136 - val_loss: 7.4586 - val_accuracy: 0.0365
Epoch 20/100
60/60 [==============================] - 1s 15ms/step - loss: 2.8441 - accuracy: 0.4426 - val_loss: 7.4877 - val_accuracy: 0.0292
Epoch 21/100
60/60 [==============================] - 1s 15ms/step - loss: 2.7577 - accuracy: 0.4572 - val_loss: 7.6684 - val_accuracy: 0.0333
Epoch 22/100
60/60 [==============================] - 1s 15ms/step - loss: 2.6243 - accuracy: 0.4806 - val_loss: 7.7528 - val_accuracy: 0.0323
Epoch 23/100
60/60 [==============================] - 1s 15ms/step - loss: 2.5463 - accuracy: 0.4947 - val_loss: 8.0556 - val_accuracy: 0.0333
Epoch 24/100
60/60 [==============================] - 1s 14ms/step - loss: 2.4540 - accuracy: 0.5124 - val_loss: 7.9396 - val_accuracy: 0.0344
Epoch 25/100
60/60 [==============================] - 1s 15ms/step - loss: 2.4033 - accuracy: 0.5121 - val_loss: 7.9808 - val_accuracy: 0.0312
Epoch 26/100
60/60 [==============================] - 1s 15ms/step - loss: 2.3429 - accuracy: 0.5306 - val_loss: 7.8360 - val_accuracy: 0.0281
Epoch 27/100
60/60 [==============================] - 1s 15ms/step - loss: 2.2904 - accuracy: 0.5449 - val_loss: 8.1236 - val_accuracy: 0.0312
Epoch 28/100
60/60 [==============================] - 1s 15ms/step - loss: 2.2013 - accuracy: 0.5619 - val_loss: 8.0642 - val_accuracy: 0.0292
Epoch 29/100
60/60 [==============================] - 1s 14ms/step - loss: 2.1430 - accuracy: 0.5587 - val_loss: 8.2606 - val_accuracy: 0.0260
Epoch 30/100
60/60 [==============================] - 1s 15ms/step - loss: 2.1439 - accuracy: 0.5595 - val_loss: 8.2415 - val_accuracy: 0.0198
Epoch 31/100
60/60 [==============================] - 1s 14ms/step - loss: 2.0865 - accuracy: 0.5658 - val_loss: 8.2529 - val_accuracy: 0.0250
Epoch 32/100
60/60 [==============================] - 1s 14ms/step - loss: 2.0241 - accuracy: 0.5866 - val_loss: 8.3251 - val_accuracy: 0.0333
Epoch 33/100
60/60 [==============================] - 1s 15ms/step - loss: 1.9881 - accuracy: 0.5931 - val_loss: 8.2281 - val_accuracy: 0.0281
Epoch 34/100
60/60 [==============================] - 1s 14ms/step - loss: 1.9819 - accuracy: 0.5926 - val_loss: 8.3426 - val_accuracy: 0.0229
Epoch 35/100
60/60 [==============================] - 1s 14ms/step - loss: 1.9113 - accuracy: 0.6004 - val_loss: 8.3815 - val_accuracy: 0.0240
Epoch 36/100
60/60 [==============================] - 1s 15ms/step - loss: 1.8948 - accuracy: 0.6033 - val_loss: 8.6785 - val_accuracy: 0.0281
Epoch 37/100
60/60 [==============================] - 1s 14ms/step - loss: 1.8498 - accuracy: 0.6140 - val_loss: 8.7488 - val_accuracy: 0.0250
Epoch 38/100
60/60 [==============================] - 1s 15ms/step - loss: 1.8235 - accuracy: 0.6127 - val_loss: 8.7774 - val_accuracy: 0.0260
Epoch 39/100
60/60 [==============================] - 1s 14ms/step - loss: 1.7960 - accuracy: 0.6150 - val_loss: 8.2597 - val_accuracy: 0.0240
Epoch 40/100
60/60 [==============================] - 1s 15ms/step - loss: 1.7281 - accuracy: 0.6306 - val_loss: 8.5127 - val_accuracy: 0.0229
Epoch 41/100
60/60 [==============================] - 1s 14ms/step - loss: 1.7142 - accuracy: 0.6340 - val_loss: 9.0598 - val_accuracy: 0.0240
Epoch 42/100
60/60 [==============================] - 1s 14ms/step - loss: 1.7085 - accuracy: 0.6332 - val_loss: 8.8107 - val_accuracy: 0.0260
Epoch 43/100
60/60 [==============================] - 1s 15ms/step - loss: 1.6801 - accuracy: 0.6361 - val_loss: 8.6091 - val_accuracy: 0.0271
Epoch 44/100
60/60 [==============================] - 1s 14ms/step - loss: 1.6387 - accuracy: 0.6439 - val_loss: 8.6105 - val_accuracy: 0.0208
Epoch 45/100
60/60 [==============================] - 1s 15ms/step - loss: 1.6273 - accuracy: 0.6405 - val_loss: 8.7644 - val_accuracy: 0.0292
Epoch 46/100
60/60 [==============================] - 1s 15ms/step - loss: 1.6046 - accuracy: 0.6523 - val_loss: 9.0368 - val_accuracy: 0.0219
Epoch 47/100
60/60 [==============================] - 1s 15ms/step - loss: 1.6345 - accuracy: 0.6429 - val_loss: 8.7563 - val_accuracy: 0.0198
Epoch 48/100
60/60 [==============================] - 1s 14ms/step - loss: 1.5903 - accuracy: 0.6489 - val_loss: 8.9499 - val_accuracy: 0.0323
Epoch 49/100
60/60 [==============================] - 1s 14ms/step - loss: 1.5817 - accuracy: 0.6536 - val_loss: 9.0135 - val_accuracy: 0.0260
Epoch 50/100
60/60 [==============================] - 1s 15ms/step - loss: 1.5405 - accuracy: 0.6640 - val_loss: 9.2398 - val_accuracy: 0.0281
Epoch 51/100
60/60 [==============================] - 1s 14ms/step - loss: 1.5808 - accuracy: 0.6528 - val_loss: 8.9158 - val_accuracy: 0.0271
Epoch 52/100
60/60 [==============================] - 1s 15ms/step - loss: 1.4969 - accuracy: 0.6611 - val_loss: 8.9515 - val_accuracy: 0.0229
Epoch 53/100
60/60 [==============================] - 1s 15ms/step - loss: 1.5401 - accuracy: 0.6642 - val_loss: 8.6358 - val_accuracy: 0.0229
Epoch 54/100
60/60 [==============================] - 1s 15ms/step - loss: 1.4868 - accuracy: 0.6648 - val_loss: 9.0517 - val_accuracy: 0.0250
Epoch 55/100
60/60 [==============================] - 1s 15ms/step - loss: 1.4894 - accuracy: 0.6713 - val_loss: 9.3730 - val_accuracy: 0.0260
Epoch 56/100
60/60 [==============================] - 1s 15ms/step - loss: 1.4453 - accuracy: 0.6739 - val_loss: 9.1175 - val_accuracy: 0.0271
Epoch 57/100
60/60 [==============================] - 1s 15ms/step - loss: 1.4595 - accuracy: 0.6687 - val_loss: 9.2411 - val_accuracy: 0.0302
Epoch 58/100
60/60 [==============================] - 1s 15ms/step - loss: 1.4370 - accuracy: 0.6754 - val_loss: 8.9506 - val_accuracy: 0.0260
Epoch 59/100
60/60 [==============================] - 1s 15ms/step - loss: 1.4224 - accuracy: 0.6788 - val_loss: 8.8048 - val_accuracy: 0.0260
Epoch 60/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3611 - accuracy: 0.6892 - val_loss: 9.3025 - val_accuracy: 0.0240
Epoch 61/100
60/60 [==============================] - 1s 16ms/step - loss: 1.3914 - accuracy: 0.6809 - val_loss: 8.9500 - val_accuracy: 0.0198
Epoch 62/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3780 - accuracy: 0.6908 - val_loss: 9.0820 - val_accuracy: 0.0250
Epoch 63/100
60/60 [==============================] - 1s 16ms/step - loss: 1.3767 - accuracy: 0.6892 - val_loss: 9.2361 - val_accuracy: 0.0229
Epoch 64/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3441 - accuracy: 0.6921 - val_loss: 9.2536 - val_accuracy: 0.0292
Epoch 65/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3204 - accuracy: 0.6898 - val_loss: 8.9040 - val_accuracy: 0.0281
Epoch 66/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3559 - accuracy: 0.6978 - val_loss: 9.2070 - val_accuracy: 0.0292
Epoch 67/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3248 - accuracy: 0.7023 - val_loss: 9.4437 - val_accuracy: 0.0240
Epoch 68/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3485 - accuracy: 0.6895 - val_loss: 8.9829 - val_accuracy: 0.0292
Epoch 69/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3409 - accuracy: 0.6921 - val_loss: 9.2650 - val_accuracy: 0.0333
Epoch 70/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3217 - accuracy: 0.6978 - val_loss: 9.3985 - val_accuracy: 0.0385
Epoch 71/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3330 - accuracy: 0.6973 - val_loss: 8.7960 - val_accuracy: 0.0250
Epoch 72/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2885 - accuracy: 0.7057 - val_loss: 9.1471 - val_accuracy: 0.0240
Epoch 73/100
60/60 [==============================] - 1s 16ms/step - loss: 1.2690 - accuracy: 0.7038 - val_loss: 9.7797 - val_accuracy: 0.0333
Epoch 74/100
60/60 [==============================] - 1s 15ms/step - loss: 1.3394 - accuracy: 0.6976 - val_loss: 9.3903 - val_accuracy: 0.0281
Epoch 75/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2552 - accuracy: 0.7106 - val_loss: 9.1970 - val_accuracy: 0.0302
Epoch 76/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2583 - accuracy: 0.7025 - val_loss: 9.0764 - val_accuracy: 0.0198
Epoch 77/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2896 - accuracy: 0.6991 - val_loss: 8.8885 - val_accuracy: 0.0240
Epoch 78/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2194 - accuracy: 0.7114 - val_loss: 9.1522 - val_accuracy: 0.0188
Epoch 79/100
60/60 [==============================] - 1s 16ms/step - loss: 1.2502 - accuracy: 0.7122 - val_loss: 9.6707 - val_accuracy: 0.0177
Epoch 80/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2538 - accuracy: 0.7044 - val_loss: 9.1766 - val_accuracy: 0.0281
Epoch 81/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2252 - accuracy: 0.7156 - val_loss: 9.4022 - val_accuracy: 0.0292
Epoch 82/100
60/60 [==============================] - 1s 16ms/step - loss: 1.2484 - accuracy: 0.7140 - val_loss: 8.7856 - val_accuracy: 0.0229
Epoch 83/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2305 - accuracy: 0.7049 - val_loss: 8.9644 - val_accuracy: 0.0219
Epoch 84/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2322 - accuracy: 0.7020 - val_loss: 9.0118 - val_accuracy: 0.0229
Epoch 85/100
60/60 [==============================] - 1s 15ms/step - loss: 1.1914 - accuracy: 0.7158 - val_loss: 9.2694 - val_accuracy: 0.0219
Epoch 86/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2036 - accuracy: 0.7189 - val_loss: 9.2791 - val_accuracy: 0.0229
Epoch 87/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2168 - accuracy: 0.7247 - val_loss: 9.4464 - val_accuracy: 0.0229
Epoch 88/100
60/60 [==============================] - 1s 15ms/step - loss: 1.1524 - accuracy: 0.7247 - val_loss: 9.3727 - val_accuracy: 0.0208
Epoch 89/100
60/60 [==============================] - 1s 15ms/step - loss: 1.1201 - accuracy: 0.7268 - val_loss: 9.4981 - val_accuracy: 0.0250
Epoch 90/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2244 - accuracy: 0.7088 - val_loss: 9.1056 - val_accuracy: 0.0208
Epoch 91/100
60/60 [==============================] - 1s 16ms/step - loss: 1.1983 - accuracy: 0.7249 - val_loss: 9.4158 - val_accuracy: 0.0219
Epoch 92/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2184 - accuracy: 0.7132 - val_loss: 8.8080 - val_accuracy: 0.0250
Epoch 93/100
60/60 [==============================] - 1s 15ms/step - loss: 1.1576 - accuracy: 0.7327 - val_loss: 9.3510 - val_accuracy: 0.0229
Epoch 94/100
60/60 [==============================] - 1s 15ms/step - loss: 1.2156 - accuracy: 0.7187 - val_loss: 9.1901 - val_accuracy: 0.0208
Epoch 95/100
60/60 [==============================] - 1s 15ms/step - loss: 1.1925 - accuracy: 0.7236 - val_loss: 9.1375 - val_accuracy: 0.0198
Epoch 96/100
60/60 [==============================] - 1s 16ms/step - loss: 1.1486 - accuracy: 0.7299 - val_loss: 9.2591 - val_accuracy: 0.0198
Epoch 97/100
60/60 [==============================] - 1s 15ms/step - loss: 1.1739 - accuracy: 0.7231 - val_loss: 9.1826 - val_accuracy: 0.0177
Epoch 98/100
60/60 [==============================] - 1s 15ms/step - loss: 1.1284 - accuracy: 0.7296 - val_loss: 9.2003 - val_accuracy: 0.0198
Epoch 99/100
60/60 [==============================] - 1s 16ms/step - loss: 1.1624 - accuracy: 0.7202 - val_loss: 9.0584 - val_accuracy: 0.0208
Epoch 100/100
60/60 [==============================] - 1s 16ms/step - loss: 1.0933 - accuracy: 0.7393 - val_loss: 9.7638 - val_accuracy: 0.0198
Model Accuracy: 1.98%
1/1 [==============================] - 0s 61ms/step
Confidence of Each Genre:
Action: 0.11%
Action, Adventure: 0.09%
Action, Adventure, Animation, Comedy, Family: 0.04%
Action, Adventure, Animation, Comedy, Family, Fantasy, Romance: 0.12%
Action, Adventure, Animation, Comedy, Family, Fantasy, Science Fiction: 0.28%
Action, Adventure, Animation, Comedy, Science Fiction: 0.06%
Action, Adventure, Animation, Family: 0.02%
Action, Adventure, Animation, Family, Fantasy: 0.06%
Action, Adventure, Animation, Fantasy, Science Fiction: 0.28%
Action, Adventure, Animation, Science Fiction, Thriller: 0.00%
Action, Adventure, Comedy: 0.11%
Action, Adventure, Comedy, Crime: 0.02%
Action, Adventure, Comedy, Crime, Drama: 0.01%
Action, Adventure, Comedy, Crime, Mystery, Thriller: 0.14%
Action, Adventure, Comedy, Crime, Romance, Thriller: 0.02%
Action, Adventure, Comedy, Crime, Thriller: 0.11%
Action, Adventure, Comedy, Drama, Family, Music, Romance: 0.12%
Action, Adventure, Comedy, Drama, Foreign: 0.01%
Action, Adventure, Comedy, Drama, Mystery: 0.07%
Action, Adventure, Comedy, Drama, Science Fiction, Thriller: 0.00%
Action, Adventure, Comedy, Family: 0.17%
Action, Adventure, Comedy, Family, Fantasy: 0.06%
Action, Adventure, Comedy, Family, Fantasy, Science Fiction: 0.04%
Action, Adventure, Comedy, Family, Science Fiction: 0.14%
Action, Adventure, Comedy, Fantasy: 0.07%
Action, Adventure, Comedy, Fantasy, Science Fiction: 0.18%
Action, Adventure, Comedy, Romance: 0.00%
Action, Adventure, Comedy, Science Fiction: 0.22%
Action, Adventure, Comedy, Science Fiction, Western: 0.00%
Action, Adventure, Comedy, Thriller: 0.15%
Action, Adventure, Comedy, Thriller, Crime: 0.00%
Action, Adventure, Comedy, Western: 0.16%
Action, Adventure, Crime: 0.14%
Action, Adventure, Crime, Drama: 0.00%
Action, Adventure, Crime, Drama, Family, Mystery, Thriller: 0.00%
Action, Adventure, Crime, Drama, Mystery, Thriller: 0.16%
Action, Adventure, Crime, Drama, Thriller: 0.00%
Action, Adventure, Crime, Drama, Thriller, Western: 0.17%
Action, Adventure, Crime, Family, Mystery, Thriller: 0.03%
Action, Adventure, Crime, Fantasy, Science Fiction: 0.17%
Action, Adventure, Crime, Mystery: 0.04%
Action, Adventure, Crime, Mystery, Thriller: 0.00%
Action, Adventure, Crime, Science Fiction, Thriller: 0.13%
Action, Adventure, Crime, Thriller: 0.07%
Action, Adventure, Drama: 0.08%
Action, Adventure, Drama, Family: 0.19%
Action, Adventure, Drama, Fantasy: 0.17%
Action, Adventure, Drama, History: 0.28%
Action, Adventure, Drama, History, Romance, War: 0.04%
Action, Adventure, Drama, History, War: 0.22%
Action, Adventure, Drama, History, Western: 0.23%
Action, Adventure, Drama, Horror, Science Fiction: 0.12%
Action, Adventure, Drama, Mystery, Romance, Fantasy: 0.09%
Action, Adventure, Drama, Mystery, Science Fiction, Thriller: 0.02%
Action, Adventure, Drama, Romance: 0.11%
Action, Adventure, Drama, Romance, Thriller: 0.02%
Action, Adventure, Drama, Thriller: 0.14%
Action, Adventure, Drama, War: 0.14%
Action, Adventure, Family: 0.11%
Action, Adventure, Family, Fantasy: 0.08%
Action, Adventure, Fantasy: 0.20%
Action, Adventure, Fantasy, Horror: 0.31%
Action, Adventure, Fantasy, Horror, Science Fiction, Thriller: 0.08%
Action, Adventure, Fantasy, Science Fiction: 0.12%
Action, Adventure, Fantasy, Science Fiction, Thriller: 0.05%
Action, Adventure, Fantasy, Thriller: 0.12%
Action, Adventure, Fantasy, War: 0.04%
Action, Adventure, History, Romance, Drama: 0.00%
Action, Adventure, History, Western: 0.09%
Action, Adventure, Horror, Science Fiction: 0.16%
Action, Adventure, Horror, Thriller: 0.03%
Action, Adventure, Mystery, Science Fiction, Thriller: 0.04%
Action, Adventure, Mystery, Thriller: 0.01%
Action, Adventure, Romance, Science Fiction, Thriller: 0.14%
Action, Adventure, Romance, Western: 0.06%
Action, Adventure, Science Fiction: 0.06%
Action, Adventure, Science Fiction, Romance: 0.18%
Action, Adventure, Science Fiction, Thriller: 0.10%
Action, Adventure, Thriller: 0.06%
Action, Adventure, Thriller, Drama: 0.13%
Action, Adventure, Thriller, Science Fiction: 0.02%
Action, Adventure, Thriller, War: 0.04%
Action, Adventure, War: 0.02%
Action, Adventure, War, History: 0.12%
Action, Adventure, War, Thriller: 0.15%
Action, Adventure, Western: 0.17%
Action, Animation: 0.04%
Action, Animation, Science Fiction: 0.10%
Action, Comedy: 0.04%
Action, Comedy, Crime: 0.02%
Action, Comedy, Crime, Drama: 0.07%
Action, Comedy, Crime, Drama, Music: 0.00%
Action, Comedy, Crime, Drama, Thriller: 0.04%
Action, Comedy, Crime, Fantasy: 0.40%
Action, Comedy, Crime, Mystery: 0.00%
Action, Comedy, Crime, Mystery, Family: 0.11%
Action, Comedy, Crime, Romance: 0.00%
Action, Comedy, Crime, Thriller: 0.14%
Action, Comedy, Documentary: 0.11%
Action, Comedy, Drama: 0.08%
Action, Comedy, Drama, Family, Thriller: 0.00%
Action, Comedy, Drama, History: 0.00%
Action, Comedy, Drama, Romance: 0.13%
Action, Comedy, Drama, Thriller: 0.00%
Action, Comedy, Drama, Western: 0.01%
Action, Comedy, Family: 0.05%
Action, Comedy, Family, Adventure: 0.09%
Action, Comedy, Fantasy: 0.17%
Action, Comedy, Fantasy, Science Fiction: 0.00%
Action, Comedy, Foreign: 0.30%
Action, Comedy, Horror: 0.03%
Action, Comedy, Horror, Mystery, Science Fiction, Thriller: 0.05%
Action, Comedy, Horror, Thriller: 0.12%
Action, Comedy, Music: 0.07%
Action, Comedy, Music, Romance, Western: 0.32%
Action, Comedy, Romance: 0.04%
Action, Comedy, Romance, Science Fiction, Thriller: 0.03%
Action, Comedy, Romance, Thriller: 0.06%
Action, Comedy, Science Fiction: 0.06%
Action, Comedy, Thriller: 0.09%

In [36]:
predicted_genre

'Documentary, Drama, History'

In [37]:
import pandas as pd

# Load your actual DataFrame
df1 = pd.read_csv("no_null_vals2.csv")

# Create a DataFrame with titles and genres
data = {
    'Title': df1['title'],
    'Genre': df1['Genre Names']
}
df = pd.DataFrame(data)

# Assuming 'predicted_genre' contains a string of genres separated by commas
predicted_genres = predicted_genre
# Split the predicted_genre into a list
genres_to_recommend = predicted_genres.split(', ')

# Convert 'Genre' to string and filter the DataFrame based on whether
# the 'Genre' column contains any of the genres in genres_to_recommend
# Also, use str.contains() for a simpler approach and handle NaN values
recommended_movies = df[df['Genre'].astype(str).apply(
    lambda x: any(genre.lower() in x.lower() for genre in genres_to_recommend))]

# Print the recommended movie titles
print("Recommended Movies based on genres:")
print(recommended_movies['Title'].tolist()[:5])

Recommended Movies based on genres:
['The Dark Knight Rises', 'King Kong', 'Titanic', 'World War Z', 'The Great Gatsby']

In [38]:
model.save('model.h5')  # saves the architecture and weights
import pickle

# Saving tokenizer
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)
import joblib

# Saving label encoder
joblib.dump(label_encoder, 'label_encoder.joblib')
word2vec_model.save("word2vec.model")

/Users/sunil/pytorch-test/env/lib/python3.8/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [45]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense, Dropout
from tensorflow.keras.utils import plot_model

# Assuming that your text preprocessing and tokenization have been completed
# and you have the following variables initialized:

# max_length: maximum length of the sequences after padding
# size_of_vocabulary: the total number of unique words in the dataset
# num_of_genres: the number of unique genres

max_length = 175
size_of_vocabulary = len(tokenizer.word_index) + 1  # replace with actual size
num_of_genres = len(tmdb2['Genre Names'].unique())  # replace with actual number

# Constructing the Neural Network Model
model = Sequential([
    Embedding(input_dim=size_of_vocabulary, output_dim=100, input_length=max_length),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(num_of_genres, activation='softmax')
])

# Compiling the model with an optimizer and loss function
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Now, let's generate the architecture diagram using TensorBoard's plotting utility
plot_model(model, to_file='/Users/sunil/Documents/SEM6/DeepLearning/final_project/architecture.png', show_shapes=True, show_layer_names=True)

# This will save the architecture diagram to a file which can then be displayed
model_architecture_path = '/Users/sunil/Documents/SEM6/DeepLearning/final_project/architecture.png'
model_architecture_path

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.

'/Users/sunil/Documents/SEM6/DeepLearning/final_project/architecture.png'

In [46]:
from tensorflow.keras.callbacks import TensorBoard
import datetime

# Directory where the TensorBoard logs will be saved
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

# Callback for TensorBoard
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

# Fit your model (make sure to include the validation data if you have it)
model.fit(X_train, y_train, epochs=100, batch_size=64, 
          validation_data=(X_test, y_test), callbacks=[tensorboard_callback])

Epoch 1/100
60/60 [==============================] - 2s 25ms/step - loss: 6.4572 - accuracy: 0.0461 - val_loss: 5.9296 - val_accuracy: 0.0625
Epoch 2/100
60/60 [==============================] - 2s 26ms/step - loss: 5.8688 - accuracy: 0.0662 - val_loss: 5.9840 - val_accuracy: 0.0865
Epoch 3/100
60/60 [==============================] - 1s 25ms/step - loss: 5.5765 - accuracy: 0.0693 - val_loss: 5.8355 - val_accuracy: 0.0854
Epoch 4/100
60/60 [==============================] - 1s 22ms/step - loss: 5.2133 - accuracy: 0.0667 - val_loss: 5.8921 - val_accuracy: 0.0865
Epoch 5/100
60/60 [==============================] - 1s 21ms/step - loss: 5.0686 - accuracy: 0.0628 - val_loss: 5.9876 - val_accuracy: 0.0823
Epoch 6/100
60/60 [==============================] - 1s 22ms/step - loss: 4.9942 - accuracy: 0.0722 - val_loss: 6.0821 - val_accuracy: 0.0823
Epoch 7/100
60/60 [==============================] - 2s 25ms/step - loss: 4.9181 - accuracy: 0.0729 - val_loss: 6.2379 - val_accuracy: 0.0635
Epoch 8/100
60/60 [==============================] - 2s 26ms/step - loss: 4.8412 - accuracy: 0.0716 - val_loss: 6.3142 - val_accuracy: 0.0896
Epoch 9/100
60/60 [==============================] - 1s 24ms/step - loss: 4.7758 - accuracy: 0.0774 - val_loss: 6.4246 - val_accuracy: 0.0708
Epoch 10/100
60/60 [==============================] - 2s 26ms/step - loss: 4.6807 - accuracy: 0.0920 - val_loss: 6.5743 - val_accuracy: 0.0583
Epoch 11/100
60/60 [==============================] - 2s 29ms/step - loss: 4.5593 - accuracy: 0.1133 - val_loss: 6.6368 - val_accuracy: 0.0437
Epoch 12/100
60/60 [==============================] - 1s 24ms/step - loss: 4.3976 - accuracy: 0.1425 - val_loss: 6.6199 - val_accuracy: 0.0396
Epoch 13/100
60/60 [==============================] - 2s 35ms/step - loss: 4.2145 - accuracy: 0.1826 - val_loss: 6.7119 - val_accuracy: 0.0396
Epoch 14/100
60/60 [==============================] - 1s 25ms/step - loss: 3.9985 - accuracy: 0.2238 - val_loss: 6.8651 - val_accuracy: 0.0375
Epoch 15/100
60/60 [==============================] - 1s 24ms/step - loss: 3.7702 - accuracy: 0.2772 - val_loss: 6.9443 - val_accuracy: 0.0396
Epoch 16/100
60/60 [==============================] - 2s 28ms/step - loss: 3.5836 - accuracy: 0.3079 - val_loss: 7.0547 - val_accuracy: 0.0375
Epoch 17/100
60/60 [==============================] - 1s 24ms/step - loss: 3.3879 - accuracy: 0.3511 - val_loss: 7.2147 - val_accuracy: 0.0396
Epoch 18/100
60/60 [==============================] - 2s 26ms/step - loss: 3.2190 - accuracy: 0.3787 - val_loss: 7.3840 - val_accuracy: 0.0396
Epoch 19/100
60/60 [==============================] - 2s 31ms/step - loss: 3.0645 - accuracy: 0.3983 - val_loss: 7.2475 - val_accuracy: 0.0365
Epoch 20/100
60/60 [==============================] - 1s 24ms/step - loss: 2.9304 - accuracy: 0.4262 - val_loss: 7.3398 - val_accuracy: 0.0396
Epoch 21/100
60/60 [==============================] - 1s 23ms/step - loss: 2.8013 - accuracy: 0.4496 - val_loss: 7.3842 - val_accuracy: 0.0354
Epoch 22/100
60/60 [==============================] - 2s 37ms/step - loss: 2.7077 - accuracy: 0.4647 - val_loss: 7.6118 - val_accuracy: 0.0323
Epoch 23/100
60/60 [==============================] - 1s 23ms/step - loss: 2.6165 - accuracy: 0.4743 - val_loss: 7.5389 - val_accuracy: 0.0302
Epoch 24/100
60/60 [==============================] - 1s 20ms/step - loss: 2.5191 - accuracy: 0.5004 - val_loss: 7.7265 - val_accuracy: 0.0260
Epoch 25/100
60/60 [==============================] - 1s 22ms/step - loss: 2.4389 - accuracy: 0.5098 - val_loss: 7.7149 - val_accuracy: 0.0292
Epoch 26/100
60/60 [==============================] - 1s 23ms/step - loss: 2.3890 - accuracy: 0.5181 - val_loss: 7.9469 - val_accuracy: 0.0344
Epoch 27/100
60/60 [==============================] - 1s 23ms/step - loss: 2.3310 - accuracy: 0.5225 - val_loss: 7.9880 - val_accuracy: 0.0240
Epoch 28/100
60/60 [==============================] - 1s 21ms/step - loss: 2.2552 - accuracy: 0.5345 - val_loss: 7.8895 - val_accuracy: 0.0281
Epoch 29/100
60/60 [==============================] - 1s 22ms/step - loss: 2.2120 - accuracy: 0.5418 - val_loss: 7.8572 - val_accuracy: 0.0333
Epoch 30/100
60/60 [==============================] - 2s 28ms/step - loss: 2.1078 - accuracy: 0.5606 - val_loss: 8.1717 - val_accuracy: 0.0229
Epoch 31/100
60/60 [==============================] - 2s 25ms/step - loss: 2.1062 - accuracy: 0.5668 - val_loss: 8.4986 - val_accuracy: 0.0260
Epoch 32/100
60/60 [==============================] - 1s 23ms/step - loss: 2.0456 - accuracy: 0.5744 - val_loss: 8.2466 - val_accuracy: 0.0260
Epoch 33/100
60/60 [==============================] - 2s 27ms/step - loss: 1.9862 - accuracy: 0.5897 - val_loss: 8.5969 - val_accuracy: 0.0292
Epoch 34/100
60/60 [==============================] - 1s 25ms/step - loss: 1.9473 - accuracy: 0.5947 - val_loss: 8.2098 - val_accuracy: 0.0312
Epoch 35/100
60/60 [==============================] - 1s 23ms/step - loss: 1.9135 - accuracy: 0.6064 - val_loss: 8.2425 - val_accuracy: 0.0302
Epoch 36/100
60/60 [==============================] - 1s 25ms/step - loss: 1.8705 - accuracy: 0.6132 - val_loss: 8.6115 - val_accuracy: 0.0271
Epoch 37/100
60/60 [==============================] - 1s 24ms/step - loss: 1.8476 - accuracy: 0.6145 - val_loss: 8.6830 - val_accuracy: 0.0323
Epoch 38/100
60/60 [==============================] - 1s 21ms/step - loss: 1.8341 - accuracy: 0.6160 - val_loss: 8.4527 - val_accuracy: 0.0281
Epoch 39/100
60/60 [==============================] - 1s 19ms/step - loss: 1.8032 - accuracy: 0.6173 - val_loss: 8.5300 - val_accuracy: 0.0281
Epoch 40/100
60/60 [==============================] - 2s 27ms/step - loss: 1.7402 - accuracy: 0.6335 - val_loss: 8.9302 - val_accuracy: 0.0333
Epoch 41/100
60/60 [==============================] - 2s 26ms/step - loss: 1.7545 - accuracy: 0.6233 - val_loss: 8.4317 - val_accuracy: 0.0271
Epoch 42/100
60/60 [==============================] - 1s 22ms/step - loss: 1.7130 - accuracy: 0.6278 - val_loss: 8.6162 - val_accuracy: 0.0302
Epoch 43/100
60/60 [==============================] - 2s 28ms/step - loss: 1.6943 - accuracy: 0.6332 - val_loss: 8.4777 - val_accuracy: 0.0260
Epoch 44/100
60/60 [==============================] - 2s 30ms/step - loss: 1.6650 - accuracy: 0.6431 - val_loss: 8.7457 - val_accuracy: 0.0312
Epoch 45/100
60/60 [==============================] - 2s 30ms/step - loss: 1.6226 - accuracy: 0.6338 - val_loss: 8.7696 - val_accuracy: 0.0281
Epoch 46/100
60/60 [==============================] - 1s 23ms/step - loss: 1.6202 - accuracy: 0.6444 - val_loss: 8.8639 - val_accuracy: 0.0281
Epoch 47/100
60/60 [==============================] - 2s 30ms/step - loss: 1.5612 - accuracy: 0.6533 - val_loss: 8.8919 - val_accuracy: 0.0323
Epoch 48/100
60/60 [==============================] - 2s 28ms/step - loss: 1.5713 - accuracy: 0.6512 - val_loss: 8.8845 - val_accuracy: 0.0302
Epoch 49/100
60/60 [==============================] - 1s 25ms/step - loss: 1.5683 - accuracy: 0.6515 - val_loss: 8.6554 - val_accuracy: 0.0281
Epoch 50/100
60/60 [==============================] - 2s 29ms/step - loss: 1.5685 - accuracy: 0.6512 - val_loss: 8.6910 - val_accuracy: 0.0219
Epoch 51/100
60/60 [==============================] - 2s 27ms/step - loss: 1.4951 - accuracy: 0.6569 - val_loss: 8.6429 - val_accuracy: 0.0240
Epoch 52/100
60/60 [==============================] - 2s 34ms/step - loss: 1.4794 - accuracy: 0.6728 - val_loss: 8.7088 - val_accuracy: 0.0240
Epoch 53/100
60/60 [==============================] - 1s 24ms/step - loss: 1.4835 - accuracy: 0.6655 - val_loss: 8.8657 - val_accuracy: 0.0271
Epoch 54/100
60/60 [==============================] - 2s 26ms/step - loss: 1.4673 - accuracy: 0.6689 - val_loss: 9.0111 - val_accuracy: 0.0229
Epoch 55/100
60/60 [==============================] - 1s 25ms/step - loss: 1.4375 - accuracy: 0.6741 - val_loss: 9.0740 - val_accuracy: 0.0250
Epoch 56/100
60/60 [==============================] - 1s 23ms/step - loss: 1.4416 - accuracy: 0.6752 - val_loss: 9.2952 - val_accuracy: 0.0271
Epoch 57/100
60/60 [==============================] - 2s 32ms/step - loss: 1.4180 - accuracy: 0.6754 - val_loss: 8.9420 - val_accuracy: 0.0219
Epoch 58/100
60/60 [==============================] - 2s 31ms/step - loss: 1.4683 - accuracy: 0.6689 - val_loss: 9.0032 - val_accuracy: 0.0292
Epoch 59/100
60/60 [==============================] - 2s 25ms/step - loss: 1.3837 - accuracy: 0.6788 - val_loss: 9.2287 - val_accuracy: 0.0240
Epoch 60/100
60/60 [==============================] - 2s 26ms/step - loss: 1.4001 - accuracy: 0.6760 - val_loss: 9.2216 - val_accuracy: 0.0229
Epoch 61/100
60/60 [==============================] - 2s 35ms/step - loss: 1.3588 - accuracy: 0.6968 - val_loss: 8.9500 - val_accuracy: 0.0250
Epoch 62/100
60/60 [==============================] - 2s 26ms/step - loss: 1.4029 - accuracy: 0.6853 - val_loss: 8.9144 - val_accuracy: 0.0219
Epoch 63/100
60/60 [==============================] - 2s 27ms/step - loss: 1.3869 - accuracy: 0.6780 - val_loss: 9.2285 - val_accuracy: 0.0198
Epoch 64/100
60/60 [==============================] - 1s 23ms/step - loss: 1.3405 - accuracy: 0.6859 - val_loss: 9.2332 - val_accuracy: 0.0219
Epoch 65/100
60/60 [==============================] - 1s 22ms/step - loss: 1.3522 - accuracy: 0.6817 - val_loss: 8.9884 - val_accuracy: 0.0260
Epoch 66/100
60/60 [==============================] - 1s 23ms/step - loss: 1.3277 - accuracy: 0.7015 - val_loss: 9.0638 - val_accuracy: 0.0240
Epoch 67/100
60/60 [==============================] - 2s 27ms/step - loss: 1.2952 - accuracy: 0.6939 - val_loss: 9.6523 - val_accuracy: 0.0219
Epoch 68/100
60/60 [==============================] - 2s 25ms/step - loss: 1.3681 - accuracy: 0.6846 - val_loss: 9.3314 - val_accuracy: 0.0271
Epoch 69/100
60/60 [==============================] - 2s 27ms/step - loss: 1.2839 - accuracy: 0.7072 - val_loss: 9.2650 - val_accuracy: 0.0240
Epoch 70/100
60/60 [==============================] - 2s 26ms/step - loss: 1.2829 - accuracy: 0.6973 - val_loss: 9.2271 - val_accuracy: 0.0271
Epoch 71/100
60/60 [==============================] - 2s 26ms/step - loss: 1.2567 - accuracy: 0.7096 - val_loss: 9.7617 - val_accuracy: 0.0219
Epoch 72/100
60/60 [==============================] - 2s 27ms/step - loss: 1.2822 - accuracy: 0.7051 - val_loss: 9.5368 - val_accuracy: 0.0271
Epoch 73/100
60/60 [==============================] - 1s 22ms/step - loss: 1.2829 - accuracy: 0.7004 - val_loss: 9.0983 - val_accuracy: 0.0219
Epoch 74/100
60/60 [==============================] - 2s 27ms/step - loss: 1.2986 - accuracy: 0.7036 - val_loss: 9.5080 - val_accuracy: 0.0219
Epoch 75/100
60/60 [==============================] - 1s 22ms/step - loss: 1.2913 - accuracy: 0.7041 - val_loss: 9.5852 - val_accuracy: 0.0240
Epoch 76/100
60/60 [==============================] - 2s 26ms/step - loss: 1.3145 - accuracy: 0.6997 - val_loss: 9.4611 - val_accuracy: 0.0219
Epoch 77/100
60/60 [==============================] - 1s 24ms/step - loss: 1.2655 - accuracy: 0.7088 - val_loss: 9.5514 - val_accuracy: 0.0198
Epoch 78/100
60/60 [==============================] - 1s 24ms/step - loss: 1.2781 - accuracy: 0.7025 - val_loss: 9.7297 - val_accuracy: 0.0229
Epoch 79/100
60/60 [==============================] - 1s 20ms/step - loss: 1.2600 - accuracy: 0.7067 - val_loss: 9.1169 - val_accuracy: 0.0229
Epoch 80/100
60/60 [==============================] - 1s 21ms/step - loss: 1.2144 - accuracy: 0.7122 - val_loss: 9.2009 - val_accuracy: 0.0156
Epoch 81/100
60/60 [==============================] - 1s 24ms/step - loss: 1.1893 - accuracy: 0.7150 - val_loss: 9.4761 - val_accuracy: 0.0229
Epoch 82/100
60/60 [==============================] - 1s 21ms/step - loss: 1.2539 - accuracy: 0.7103 - val_loss: 9.7073 - val_accuracy: 0.0260
Epoch 83/100
60/60 [==============================] - 1s 23ms/step - loss: 1.2269 - accuracy: 0.7148 - val_loss: 9.1844 - val_accuracy: 0.0219
Epoch 84/100
60/60 [==============================] - 1s 20ms/step - loss: 1.2187 - accuracy: 0.7135 - val_loss: 9.5023 - val_accuracy: 0.0208
Epoch 85/100
60/60 [==============================] - 1s 22ms/step - loss: 1.2050 - accuracy: 0.7137 - val_loss: 9.4256 - val_accuracy: 0.0229
Epoch 86/100
60/60 [==============================] - 2s 25ms/step - loss: 1.2403 - accuracy: 0.7195 - val_loss: 9.2440 - val_accuracy: 0.0208
Epoch 87/100
60/60 [==============================] - 1s 21ms/step - loss: 1.1969 - accuracy: 0.7137 - val_loss: 9.2059 - val_accuracy: 0.0198
Epoch 88/100
60/60 [==============================] - 1s 21ms/step - loss: 1.1300 - accuracy: 0.7299 - val_loss: 9.5058 - val_accuracy: 0.0219
Epoch 89/100
60/60 [==============================] - 1s 23ms/step - loss: 1.1898 - accuracy: 0.7182 - val_loss: 9.4358 - val_accuracy: 0.0208
Epoch 90/100
60/60 [==============================] - 1s 21ms/step - loss: 1.2069 - accuracy: 0.7142 - val_loss: 9.7040 - val_accuracy: 0.0208
Epoch 91/100
60/60 [==============================] - 1s 21ms/step - loss: 1.1444 - accuracy: 0.7411 - val_loss: 9.6689 - val_accuracy: 0.0198
Epoch 92/100
60/60 [==============================] - 2s 28ms/step - loss: 1.1912 - accuracy: 0.7205 - val_loss: 9.4987 - val_accuracy: 0.0198
Epoch 93/100
60/60 [==============================] - 2s 26ms/step - loss: 1.1661 - accuracy: 0.7301 - val_loss: 9.5175 - val_accuracy: 0.0167
Epoch 94/100
60/60 [==============================] - 1s 25ms/step - loss: 1.1482 - accuracy: 0.7312 - val_loss: 9.8982 - val_accuracy: 0.0271
Epoch 95/100
60/60 [==============================] - 1s 23ms/step - loss: 1.1564 - accuracy: 0.7312 - val_loss: 9.4343 - val_accuracy: 0.0167
Epoch 96/100
60/60 [==============================] - 1s 21ms/step - loss: 1.1247 - accuracy: 0.7299 - val_loss: 10.1611 - val_accuracy: 0.0167
Epoch 97/100
60/60 [==============================] - 1s 20ms/step - loss: 1.1624 - accuracy: 0.7317 - val_loss: 9.3801 - val_accuracy: 0.0156
Epoch 98/100
60/60 [==============================] - 2s 27ms/step - loss: 1.1469 - accuracy: 0.7361 - val_loss: 9.5704 - val_accuracy: 0.0167
Epoch 99/100
60/60 [==============================] - 2s 25ms/step - loss: 1.1270 - accuracy: 0.7291 - val_loss: 9.8988 - val_accuracy: 0.0177
Epoch 100/100
60/60 [==============================] - 2s 33ms/step - loss: 1.1160 - accuracy: 0.7369 - val_loss: 9.7817 - val_accuracy: 0.0177